from enum import Enum
class AbilityLookup(Enum):
    Bulbasaur = {'abilities': {0: 'Overgrow', 'H': 'Chlorophyll'}}
    Ivysaur = {'abilities': {0: 'Overgrow', 'H': 'Chlorophyll'}}
    Venusaur = {'abilities': {0: 'Overgrow', 'H': 'Chlorophyll'}}
    Venusaurmega = {'abilities': {0: 'Thick Fat'}}
    Venusaurgmax = {'abilities': {0: 'Overgrow', 'H': 'Chlorophyll'}}
    Charmander = {'abilities': {0: 'Blaze', 'H': 'Solar Power'}}
    Charmeleon = {'abilities': {0: 'Blaze', 'H': 'Solar Power'}}
    Charizard = {'abilities': {0: 'Blaze', 'H': 'Solar Power'}}
    Charizardmegax = {'abilities': {0: 'Tough Claws'}}
    Charizardmegay = {'abilities': {0: 'Drought'}}
    Charizardgmax = {'abilities': {0: 'Blaze', 'H': 'Solar Power'}}
    Squirtle = {'abilities': {0: 'Torrent', 'H': 'Rain Dish'}}
    Wartortle = {'abilities': {0: 'Torrent', 'H': 'Rain Dish'}}
    Blastoise = {'abilities': {0: 'Torrent', 'H': 'Rain Dish'}}
    Blastoisemega = {'abilities': {0: 'Mega Launcher'}}
    Blastoisegmax = {'abilities': {0: 'Torrent', 'H': 'Rain Dish'}}
    Caterpie = {'abilities': {0: 'Shield Dust', 'H': 'Run Away'}}
    Metapod = {'abilities': {0: 'Shed Skin'}}
    Butterfree = {'abilities': {0: 'Compound Eyes', 'H': 'Tinted Lens'}}
    Butterfreegmax = {'abilities': {0: 'Compound Eyes', 'H': 'Tinted Lens'}}
    Weedle = {'abilities': {0: 'Shield Dust', 'H': 'Run Away'}}
    Kakuna = {'abilities': {0: 'Shed Skin'}}
    Beedrill = {'abilities': {0: 'Swarm', 'H': 'Sniper'}}
    Beedrillmega = {'abilities': {0: 'Adaptability'}}
    Pidgey = {'abilities': {0: 'Keen Eye', 1: 'Tangled Feet', 'H': 'Big Pecks'}}
    Pidgeotto = {'abilities': {0: 'Keen Eye', 1: 'Tangled Feet', 'H': 'Big Pecks'}}
    Pidgeot = {'abilities': {0: 'Keen Eye', 1: 'Tangled Feet', 'H': 'Big Pecks'}}
    Pidgeotmega = {'abilities': {0: 'No Guard'}}
    Rattata = {'abilities': {0: 'Run Away', 1: 'Guts', 'H': 'Hustle'}}
    Rattataalola = {'abilities': {0: 'Gluttony', 1: 'Hustle', 'H': 'Thick Fat'}}
    Raticate = {'abilities': {0: 'Run Away', 1: 'Guts', 'H': 'Hustle'}}
    Raticatealola = {'abilities': {0: 'Gluttony', 1: 'Hustle', 'H': 'Thick Fat'}}
    Raticatealolatotem = {'abilities': {0: 'Thick Fat'}}
    Spearow = {'abilities': {0: 'Keen Eye', 'H': 'Sniper'}}
    Fearow = {'abilities': {0: 'Keen Eye', 'H': 'Sniper'}}
    Ekans = {'abilities': {0: 'Intimidate', 1: 'Shed Skin', 'H': 'Unnerve'}}
    Arbok = {'abilities': {0: 'Intimidate', 1: 'Shed Skin', 'H': 'Unnerve'}}
    Pikachu = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachucosplay = {'abilities': {0: 'Lightning Rod'}}
    Pikachurockstar = {'abilities': {0: 'Lightning Rod'}}
    Pikachubelle = {'abilities': {0: 'Lightning Rod'}}
    Pikachupopstar = {'abilities': {0: 'Lightning Rod'}}
    Pikachuphd = {'abilities': {0: 'Lightning Rod'}}
    Pikachulibre = {'abilities': {0: 'Lightning Rod'}}
    Pikachuoriginal = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachuhoenn = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachusinnoh = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachuunova = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachukalos = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachualola = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachupartner = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachustarter = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachugmax = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pikachuworld = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Raichu = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Raichualola = {'abilities': {0: 'Surge Surfer'}}
    Sandshrew = {'abilities': {0: 'Sand Veil', 'H': 'Sand Rush'}}
    Sandshrewalola = {'abilities': {0: 'Snow Cloak', 'H': 'Slush Rush'}}
    Sandslash = {'abilities': {0: 'Sand Veil', 'H': 'Sand Rush'}}
    Sandslashalola = {'abilities': {0: 'Snow Cloak', 'H': 'Slush Rush'}}
    Nidoranf = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Hustle'}}
    Nidorina = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Hustle'}}
    Nidoqueen = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Sheer Force'}}
    Nidoranm = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Hustle'}}
    Nidorino = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Hustle'}}
    Nidoking = {'abilities': {0: 'Poison Point', 1: 'Rivalry', 'H': 'Sheer Force'}}
    Clefairy = {'abilities': {0: 'Cute Charm', 1: 'Magic Guard', 'H': 'Friend Guard'}}
    Clefable = {'abilities': {0: 'Cute Charm', 1: 'Magic Guard', 'H': 'Unaware'}}
    Vulpix = {'abilities': {0: 'Flash Fire', 'H': 'Drought'}}
    Vulpixalola = {'abilities': {0: 'Snow Cloak', 'H': 'Snow Warning'}}
    Ninetales = {'abilities': {0: 'Flash Fire', 'H': 'Drought'}}
    Ninetalesalola = {'abilities': {0: 'Snow Cloak', 'H': 'Snow Warning'}}
    Jigglypuff = {'abilities': {0: 'Cute Charm', 1: 'Competitive', 'H': 'Friend Guard'}}
    Wigglytuff = {'abilities': {0: 'Cute Charm', 1: 'Competitive', 'H': 'Frisk'}}
    Zubat = {'abilities': {0: 'Inner Focus', 'H': 'Infiltrator'}}
    Golbat = {'abilities': {0: 'Inner Focus', 'H': 'Infiltrator'}}
    Oddish = {'abilities': {0: 'Chlorophyll', 'H': 'Run Away'}}
    Gloom = {'abilities': {0: 'Chlorophyll', 'H': 'Stench'}}
    Vileplume = {'abilities': {0: 'Chlorophyll', 'H': 'Effect Spore'}}
    Paras = {'abilities': {0: 'Effect Spore', 1: 'Dry Skin', 'H': 'Damp'}}
    Parasect = {'abilities': {0: 'Effect Spore', 1: 'Dry Skin', 'H': 'Damp'}}
    Venonat = {'abilities': {0: 'Compound Eyes', 1: 'Tinted Lens', 'H': 'Run Away'}}
    Venomoth = {'abilities': {0: 'Shield Dust', 1: 'Tinted Lens', 'H': 'Wonder Skin'}}
    Diglett = {'abilities': {0: 'Sand Veil', 1: 'Arena Trap', 'H': 'Sand Force'}}
    Diglettalola = {'abilities': {0: 'Sand Veil', 1: 'Tangling Hair', 'H': 'Sand Force'}}
    Dugtrio = {'abilities': {0: 'Sand Veil', 1: 'Arena Trap', 'H': 'Sand Force'}}
    Dugtrioalola = {'abilities': {0: 'Sand Veil', 1: 'Tangling Hair', 'H': 'Sand Force'}}
    Meowth = {'abilities': {0: 'Pickup', 1: 'Technician', 'H': 'Unnerve'}}
    Meowthalola = {'abilities': {0: 'Pickup', 1: 'Technician', 'H': 'Rattled'}}
    Meowthgalar = {'abilities': {0: 'Pickup', 1: 'Tough Claws', 'H': 'Unnerve'}}
    Meowthgmax = {'abilities': {0: 'Pickup', 1: 'Technician', 'H': 'Unnerve'}}
    Persian = {'abilities': {0: 'Limber', 1: 'Technician', 'H': 'Unnerve'}}
    Persianalola = {'abilities': {0: 'Fur Coat', 1: 'Technician', 'H': 'Rattled'}}
    Psyduck = {'abilities': {0: 'Damp', 1: 'Cloud Nine', 'H': 'Swift Swim'}}
    Golduck = {'abilities': {0: 'Damp', 1: 'Cloud Nine', 'H': 'Swift Swim'}}
    Mankey = {'abilities': {0: 'Vital Spirit', 1: 'Anger Point', 'H': 'Defiant'}}
    Primeape = {'abilities': {0: 'Vital Spirit', 1: 'Anger Point', 'H': 'Defiant'}}
    Growlithe = {'abilities': {0: 'Intimidate', 1: 'Flash Fire', 'H': 'Justified'}}
    Arcanine = {'abilities': {0: 'Intimidate', 1: 'Flash Fire', 'H': 'Justified'}}
    Poliwag = {'abilities': {0: 'Water Absorb', 1: 'Damp', 'H': 'Swift Swim'}}
    Poliwhirl = {'abilities': {0: 'Water Absorb', 1: 'Damp', 'H': 'Swift Swim'}}
    Poliwrath = {'abilities': {0: 'Water Absorb', 1: 'Damp', 'H': 'Swift Swim'}}
    Abra = {'abilities': {0: 'Synchronize', 1: 'Inner Focus', 'H': 'Magic Guard'}}
    Kadabra = {'abilities': {0: 'Synchronize', 1: 'Inner Focus', 'H': 'Magic Guard'}}
    Alakazam = {'abilities': {0: 'Synchronize', 1: 'Inner Focus', 'H': 'Magic Guard'}}
    Alakazammega = {'abilities': {0: 'Trace'}}
    Machop = {'abilities': {0: 'Guts', 1: 'No Guard', 'H': 'Steadfast'}}
    Machoke = {'abilities': {0: 'Guts', 1: 'No Guard', 'H': 'Steadfast'}}
    Machamp = {'abilities': {0: 'Guts', 1: 'No Guard', 'H': 'Steadfast'}}
    Machampgmax = {'abilities': {0: 'Guts', 1: 'No Guard', 'H': 'Steadfast'}}
    Bellsprout = {'abilities': {0: 'Chlorophyll', 'H': 'Gluttony'}}
    Weepinbell = {'abilities': {0: 'Chlorophyll', 'H': 'Gluttony'}}
    Victreebel = {'abilities': {0: 'Chlorophyll', 'H': 'Gluttony'}}
    Tentacool = {'abilities': {0: 'Clear Body', 1: 'Liquid Ooze', 'H': 'Rain Dish'}}
    Tentacruel = {'abilities': {0: 'Clear Body', 1: 'Liquid Ooze', 'H': 'Rain Dish'}}
    Geodude = {'abilities': {0: 'Rock Head', 1: 'Sturdy', 'H': 'Sand Veil'}}
    Geodudealola = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Galvanize'}}
    Graveler = {'abilities': {0: 'Rock Head', 1: 'Sturdy', 'H': 'Sand Veil'}}
    Graveleralola = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Galvanize'}}
    Golem = {'abilities': {0: 'Rock Head', 1: 'Sturdy', 'H': 'Sand Veil'}}
    Golemalola = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Galvanize'}}
    Ponyta = {'abilities': {0: 'Run Away', 1: 'Flash Fire', 'H': 'Flame Body'}}
    Ponytagalar = {'abilities': {0: 'Run Away', 1: 'Pastel Veil', 'H': 'Anticipation'}}
    Rapidash = {'abilities': {0: 'Run Away', 1: 'Flash Fire', 'H': 'Flame Body'}}
    Rapidashgalar = {'abilities': {0: 'Run Away', 1: 'Pastel Veil', 'H': 'Anticipation'}}
    Slowpoke = {'abilities': {0: 'Oblivious', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Slowpokegalar = {'abilities': {0: 'Gluttony', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Slowbro = {'abilities': {0: 'Oblivious', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Slowbromega = {'abilities': {0: 'Shell Armor'}}
    Slowbrogalar = {'abilities': {0: 'Quick Draw', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Magnemite = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Analytic'}}
    Magneton = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Analytic'}}
    Farfetchd = {'abilities': {0: 'Keen Eye', 1: 'Inner Focus', 'H': 'Defiant'}}
    Farfetchdgalar = {'abilities': {0: 'Steadfast', 'H': 'Scrappy'}}
    Doduo = {'abilities': {0: 'Run Away', 1: 'Early Bird', 'H': 'Tangled Feet'}}
    Dodrio = {'abilities': {0: 'Run Away', 1: 'Early Bird', 'H': 'Tangled Feet'}}
    Seel = {'abilities': {0: 'Thick Fat', 1: 'Hydration', 'H': 'Ice Body'}}
    Dewgong = {'abilities': {0: 'Thick Fat', 1: 'Hydration', 'H': 'Ice Body'}}
    Grimer = {'abilities': {0: 'Stench', 1: 'Sticky Hold', 'H': 'Poison Touch'}}
    Grimeralola = {'abilities': {0: 'Poison Touch', 1: 'Gluttony', 'H': 'Power of Alchemy'}}
    Muk = {'abilities': {0: 'Stench', 1: 'Sticky Hold', 'H': 'Poison Touch'}}
    Mukalola = {'abilities': {0: 'Poison Touch', 1: 'Gluttony', 'H': 'Power of Alchemy'}}
    Shellder = {'abilities': {0: 'Shell Armor', 1: 'Skill Link', 'H': 'Overcoat'}}
    Cloyster = {'abilities': {0: 'Shell Armor', 1: 'Skill Link', 'H': 'Overcoat'}}
    Gastly = {'abilities': {0: 'Levitate'}}
    Haunter = {'abilities': {0: 'Levitate'}}
    Gengar = {'abilities': {0: 'Cursed Body'}}
    Gengarmega = {'abilities': {0: 'Shadow Tag'}}
    Gengargmax = {'abilities': {0: 'Cursed Body'}}
    Onix = {'abilities': {0: 'Rock Head', 1: 'Sturdy', 'H': 'Weak Armor'}}
    Drowzee = {'abilities': {0: 'Insomnia', 1: 'Forewarn', 'H': 'Inner Focus'}}
    Hypno = {'abilities': {0: 'Insomnia', 1: 'Forewarn', 'H': 'Inner Focus'}}
    Krabby = {'abilities': {0: 'Hyper Cutter', 1: 'Shell Armor', 'H': 'Sheer Force'}}
    Kingler = {'abilities': {0: 'Hyper Cutter', 1: 'Shell Armor', 'H': 'Sheer Force'}}
    Kinglergmax = {'abilities': {0: 'Hyper Cutter', 1: 'Shell Armor', 'H': 'Sheer Force'}}
    Voltorb = {'abilities': {0: 'Soundproof', 1: 'Static', 'H': 'Aftermath'}}
    Electrode = {'abilities': {0: 'Soundproof', 1: 'Static', 'H': 'Aftermath'}}
    Exeggcute = {'abilities': {0: 'Chlorophyll', 'H': 'Harvest'}}
    Exeggutor = {'abilities': {0: 'Chlorophyll', 'H': 'Harvest'}}
    Exeggutoralola = {'abilities': {0: 'Frisk', 'H': 'Harvest'}}
    Cubone = {'abilities': {0: 'Rock Head', 1: 'Lightning Rod', 'H': 'Battle Armor'}}
    Marowak = {'abilities': {0: 'Rock Head', 1: 'Lightning Rod', 'H': 'Battle Armor'}}
    Marowakalola = {'abilities': {0: 'Cursed Body', 1: 'Lightning Rod', 'H': 'Rock Head'}}
    Marowakalolatotem = {'abilities': {0: 'Rock Head'}}
    Hitmonlee = {'abilities': {0: 'Limber', 1: 'Reckless', 'H': 'Unburden'}}
    Hitmonchan = {'abilities': {0: 'Keen Eye', 1: 'Iron Fist', 'H': 'Inner Focus'}}
    Lickitung = {'abilities': {0: 'Own Tempo', 1: 'Oblivious', 'H': 'Cloud Nine'}}
    Koffing = {'abilities': {0: 'Levitate', 1: 'Neutralizing Gas', 'H': 'Stench'}}
    Weezing = {'abilities': {0: 'Levitate', 1: 'Neutralizing Gas', 'H': 'Stench'}}
    Weezinggalar = {'abilities': {0: 'Levitate', 1: 'Neutralizing Gas', 'H': 'Misty Surge'}}
    Rhyhorn = {'abilities': {0: 'Lightning Rod', 1: 'Rock Head', 'H': 'Reckless'}}
    Rhydon = {'abilities': {0: 'Lightning Rod', 1: 'Rock Head', 'H': 'Reckless'}}
    Chansey = {'abilities': {0: 'Natural Cure', 1: 'Serene Grace', 'H': 'Healer'}}
    Tangela = {'abilities': {0: 'Chlorophyll', 1: 'Leaf Guard', 'H': 'Regenerator'}}
    Kangaskhan = {'abilities': {0: 'Early Bird', 1: 'Scrappy', 'H': 'Inner Focus'}}
    Kangaskhanmega = {'abilities': {0: 'Parental Bond'}}
    Horsea = {'abilities': {0: 'Swift Swim', 1: 'Sniper', 'H': 'Damp'}}
    Seadra = {'abilities': {0: 'Poison Point', 1: 'Sniper', 'H': 'Damp'}}
    Goldeen = {'abilities': {0: 'Swift Swim', 1: 'Water Veil', 'H': 'Lightning Rod'}}
    Seaking = {'abilities': {0: 'Swift Swim', 1: 'Water Veil', 'H': 'Lightning Rod'}}
    Staryu = {'abilities': {0: 'Illuminate', 1: 'Natural Cure', 'H': 'Analytic'}}
    Starmie = {'abilities': {0: 'Illuminate', 1: 'Natural Cure', 'H': 'Analytic'}}
    Mrmime = {'abilities': {0: 'Soundproof', 1: 'Filter', 'H': 'Technician'}}
    Mrmimegalar = {'abilities': {0: 'Vital Spirit', 1: 'Screen Cleaner', 'H': 'Ice Body'}}
    Scyther = {'abilities': {0: 'Swarm', 1: 'Technician', 'H': 'Steadfast'}}
    Jynx = {'abilities': {0: 'Oblivious', 1: 'Forewarn', 'H': 'Dry Skin'}}
    Electabuzz = {'abilities': {0: 'Static', 'H': 'Vital Spirit'}}
    Magmar = {'abilities': {0: 'Flame Body', 'H': 'Vital Spirit'}}
    Pinsir = {'abilities': {0: 'Hyper Cutter', 1: 'Mold Breaker', 'H': 'Moxie'}}
    Pinsirmega = {'abilities': {0: 'Aerilate'}}
    Tauros = {'abilities': {0: 'Intimidate', 1: 'Anger Point', 'H': 'Sheer Force'}}
    Magikarp = {'abilities': {0: 'Swift Swim', 'H': 'Rattled'}}
    Gyarados = {'abilities': {0: 'Intimidate', 'H': 'Moxie'}}
    Gyaradosmega = {'abilities': {0: 'Mold Breaker'}}
    Lapras = {'abilities': {0: 'Water Absorb', 1: 'Shell Armor', 'H': 'Hydration'}}
    Laprasgmax = {'abilities': {0: 'Water Absorb', 1: 'Shell Armor', 'H': 'Hydration'}}
    Ditto = {'abilities': {0: 'Limber', 'H': 'Imposter'}}
    Eevee = {'abilities': {0: 'Run Away', 1: 'Adaptability', 'H': 'Anticipation'}}
    Eeveestarter = {'abilities': {0: 'Run Away', 1: 'Adaptability', 'H': 'Anticipation'}}
    Eeveegmax = {'abilities': {0: 'Run Away', 1: 'Adaptability', 'H': 'Anticipation'}}
    Vaporeon = {'abilities': {0: 'Water Absorb', 'H': 'Hydration'}}
    Jolteon = {'abilities': {0: 'Volt Absorb', 'H': 'Quick Feet'}}
    Flareon = {'abilities': {0: 'Flash Fire', 'H': 'Guts'}}
    Porygon = {'abilities': {0: 'Trace', 1: 'Download', 'H': 'Analytic'}}
    Omanyte = {'abilities': {0: 'Swift Swim', 1: 'Shell Armor', 'H': 'Weak Armor'}}
    Omastar = {'abilities': {0: 'Swift Swim', 1: 'Shell Armor', 'H': 'Weak Armor'}}
    Kabuto = {'abilities': {0: 'Swift Swim', 1: 'Battle Armor', 'H': 'Weak Armor'}}
    Kabutops = {'abilities': {0: 'Swift Swim', 1: 'Battle Armor', 'H': 'Weak Armor'}}
    Aerodactyl = {'abilities': {0: 'Rock Head', 1: 'Pressure', 'H': 'Unnerve'}}
    Aerodactylmega = {'abilities': {0: 'Tough Claws'}}
    Snorlax = {'abilities': {0: 'Immunity', 1: 'Thick Fat', 'H': 'Gluttony'}}
    Snorlaxgmax = {'abilities': {0: 'Immunity', 1: 'Thick Fat', 'H': 'Gluttony'}}
    Articuno = {'abilities': {0: 'Pressure', 'H': 'Snow Cloak'}}
    Articunogalar = {'abilities': {0: 'Competitive'}}
    Zapdos = {'abilities': {0: 'Pressure', 'H': 'Static'}}
    Zapdosgalar = {'abilities': {0: 'Defiant'}}
    Moltres = {'abilities': {0: 'Pressure', 'H': 'Flame Body'}}
    Moltresgalar = {'abilities': {0: 'Berserk'}}
    Dratini = {'abilities': {0: 'Shed Skin', 'H': 'Marvel Scale'}}
    Dragonair = {'abilities': {0: 'Shed Skin', 'H': 'Marvel Scale'}}
    Dragonite = {'abilities': {0: 'Inner Focus', 'H': 'Multiscale'}}
    Mewtwo = {'abilities': {0: 'Pressure', 'H': 'Unnerve'}}
    Mewtwomegax = {'abilities': {0: 'Steadfast'}}
    Mewtwomegay = {'abilities': {0: 'Insomnia'}}
    Mew = {'abilities': {0: 'Synchronize'}}
    Chikorita = {'abilities': {0: 'Overgrow', 'H': 'Leaf Guard'}}
    Bayleef = {'abilities': {0: 'Overgrow', 'H': 'Leaf Guard'}}
    Meganium = {'abilities': {0: 'Overgrow', 'H': 'Leaf Guard'}}
    Cyndaquil = {'abilities': {0: 'Blaze', 'H': 'Flash Fire'}}
    Quilava = {'abilities': {0: 'Blaze', 'H': 'Flash Fire'}}
    Typhlosion = {'abilities': {0: 'Blaze', 'H': 'Flash Fire'}}
    Totodile = {'abilities': {0: 'Torrent', 'H': 'Sheer Force'}}
    Croconaw = {'abilities': {0: 'Torrent', 'H': 'Sheer Force'}}
    Feraligatr = {'abilities': {0: 'Torrent', 'H': 'Sheer Force'}}
    Sentret = {'abilities': {0: 'Run Away', 1: 'Keen Eye', 'H': 'Frisk'}}
    Furret = {'abilities': {0: 'Run Away', 1: 'Keen Eye', 'H': 'Frisk'}}
    Hoothoot = {'abilities': {0: 'Insomnia', 1: 'Keen Eye', 'H': 'Tinted Lens'}}
    Noctowl = {'abilities': {0: 'Insomnia', 1: 'Keen Eye', 'H': 'Tinted Lens'}}
    Ledyba = {'abilities': {0: 'Swarm', 1: 'Early Bird', 'H': 'Rattled'}}
    Ledian = {'abilities': {0: 'Swarm', 1: 'Early Bird', 'H': 'Iron Fist'}}
    Spinarak = {'abilities': {0: 'Swarm', 1: 'Insomnia', 'H': 'Sniper'}}
    Ariados = {'abilities': {0: 'Swarm', 1: 'Insomnia', 'H': 'Sniper'}}
    Crobat = {'abilities': {0: 'Inner Focus', 'H': 'Infiltrator'}}
    Chinchou = {'abilities': {0: 'Volt Absorb', 1: 'Illuminate', 'H': 'Water Absorb'}}
    Lanturn = {'abilities': {0: 'Volt Absorb', 1: 'Illuminate', 'H': 'Water Absorb'}}
    Pichu = {'abilities': {0: 'Static', 'H': 'Lightning Rod'}}
    Pichuspikyeared = {'abilities': {0: 'Static'}}
    Cleffa = {'abilities': {0: 'Cute Charm', 1: 'Magic Guard', 'H': 'Friend Guard'}}
    Igglybuff = {'abilities': {0: 'Cute Charm', 1: 'Competitive', 'H': 'Friend Guard'}}
    Togepi = {'abilities': {0: 'Hustle', 1: 'Serene Grace', 'H': 'Super Luck'}}
    Togetic = {'abilities': {0: 'Hustle', 1: 'Serene Grace', 'H': 'Super Luck'}}
    Natu = {'abilities': {0: 'Synchronize', 1: 'Early Bird', 'H': 'Magic Bounce'}}
    Xatu = {'abilities': {0: 'Synchronize', 1: 'Early Bird', 'H': 'Magic Bounce'}}
    Mareep = {'abilities': {0: 'Static', 'H': 'Plus'}}
    Flaaffy = {'abilities': {0: 'Static', 'H': 'Plus'}}
    Ampharos = {'abilities': {0: 'Static', 'H': 'Plus'}}
    Ampharosmega = {'abilities': {0: 'Mold Breaker'}}
    Bellossom = {'abilities': {0: 'Chlorophyll', 'H': 'Healer'}}
    Marill = {'abilities': {0: 'Thick Fat', 1: 'Huge Power', 'H': 'Sap Sipper'}}
    Azumarill = {'abilities': {0: 'Thick Fat', 1: 'Huge Power', 'H': 'Sap Sipper'}}
    Sudowoodo = {'abilities': {0: 'Sturdy', 1: 'Rock Head', 'H': 'Rattled'}}
    Politoed = {'abilities': {0: 'Water Absorb', 1: 'Damp', 'H': 'Drizzle'}}
    Hoppip = {'abilities': {0: 'Chlorophyll', 1: 'Leaf Guard', 'H': 'Infiltrator'}}
    Skiploom = {'abilities': {0: 'Chlorophyll', 1: 'Leaf Guard', 'H': 'Infiltrator'}}
    Jumpluff = {'abilities': {0: 'Chlorophyll', 1: 'Leaf Guard', 'H': 'Infiltrator'}}
    Aipom = {'abilities': {0: 'Run Away', 1: 'Pickup', 'H': 'Skill Link'}}
    Sunkern = {'abilities': {0: 'Chlorophyll', 1: 'Solar Power', 'H': 'Early Bird'}}
    Sunflora = {'abilities': {0: 'Chlorophyll', 1: 'Solar Power', 'H': 'Early Bird'}}
    Yanma = {'abilities': {0: 'Speed Boost', 1: 'Compound Eyes', 'H': 'Frisk'}}
    Wooper = {'abilities': {0: 'Damp', 1: 'Water Absorb', 'H': 'Unaware'}}
    Quagsire = {'abilities': {0: 'Damp', 1: 'Water Absorb', 'H': 'Unaware'}}
    Espeon = {'abilities': {0: 'Synchronize', 'H': 'Magic Bounce'}}
    Umbreon = {'abilities': {0: 'Synchronize', 'H': 'Inner Focus'}}
    Murkrow = {'abilities': {0: 'Insomnia', 1: 'Super Luck', 'H': 'Prankster'}}
    Slowking = {'abilities': {0: 'Oblivious', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Slowkinggalar = {'abilities': {0: 'Curious Medicine', 1: 'Own Tempo', 'H': 'Regenerator'}}
    Misdreavus = {'abilities': {0: 'Levitate'}}
    Unown = {'abilities': {0: 'Levitate'}}
    Wobbuffet = {'abilities': {0: 'Shadow Tag', 'H': 'Telepathy'}}
    Girafarig = {'abilities': {0: 'Inner Focus', 1: 'Early Bird', 'H': 'Sap Sipper'}}
    Pineco = {'abilities': {0: 'Sturdy', 'H': 'Overcoat'}}
    Forretress = {'abilities': {0: 'Sturdy', 'H': 'Overcoat'}}
    Dunsparce = {'abilities': {0: 'Serene Grace', 1: 'Run Away', 'H': 'Rattled'}}
    Gligar = {'abilities': {0: 'Hyper Cutter', 1: 'Sand Veil', 'H': 'Immunity'}}
    Steelix = {'abilities': {0: 'Rock Head', 1: 'Sturdy', 'H': 'Sheer Force'}}
    Steelixmega = {'abilities': {0: 'Sand Force'}}
    Snubbull = {'abilities': {0: 'Intimidate', 1: 'Run Away', 'H': 'Rattled'}}
    Granbull = {'abilities': {0: 'Intimidate', 1: 'Quick Feet', 'H': 'Rattled'}}
    Qwilfish = {'abilities': {0: 'Poison Point', 1: 'Swift Swim', 'H': 'Intimidate'}}
    Scizor = {'abilities': {0: 'Swarm', 1: 'Technician', 'H': 'Light Metal'}}
    Scizormega = {'abilities': {0: 'Technician'}}
    Shuckle = {'abilities': {0: 'Sturdy', 1: 'Gluttony', 'H': 'Contrary'}}
    Heracross = {'abilities': {0: 'Swarm', 1: 'Guts', 'H': 'Moxie'}}
    Heracrossmega = {'abilities': {0: 'Skill Link'}}
    Sneasel = {'abilities': {0: 'Inner Focus', 1: 'Keen Eye', 'H': 'Pickpocket'}}
    Teddiursa = {'abilities': {0: 'Pickup', 1: 'Quick Feet', 'H': 'Honey Gather'}}
    Ursaring = {'abilities': {0: 'Guts', 1: 'Quick Feet', 'H': 'Unnerve'}}
    Slugma = {'abilities': {0: 'Magma Armor', 1: 'Flame Body', 'H': 'Weak Armor'}}
    Magcargo = {'abilities': {0: 'Magma Armor', 1: 'Flame Body', 'H': 'Weak Armor'}}
    Swinub = {'abilities': {0: 'Oblivious', 1: 'Snow Cloak', 'H': 'Thick Fat'}}
    Piloswine = {'abilities': {0: 'Oblivious', 1: 'Snow Cloak', 'H': 'Thick Fat'}}
    Corsola = {'abilities': {0: 'Hustle', 1: 'Natural Cure', 'H': 'Regenerator'}}
    Corsolagalar = {'abilities': {0: 'Weak Armor', 'H': 'Cursed Body'}}
    Remoraid = {'abilities': {0: 'Hustle', 1: 'Sniper', 'H': 'Moody'}}
    Octillery = {'abilities': {0: 'Suction Cups', 1: 'Sniper', 'H': 'Moody'}}
    Delibird = {'abilities': {0: 'Vital Spirit', 1: 'Hustle', 'H': 'Insomnia'}}
    Mantine = {'abilities': {0: 'Swift Swim', 1: 'Water Absorb', 'H': 'Water Veil'}}
    Skarmory = {'abilities': {0: 'Keen Eye', 1: 'Sturdy', 'H': 'Weak Armor'}}
    Houndour = {'abilities': {0: 'Early Bird', 1: 'Flash Fire', 'H': 'Unnerve'}}
    Houndoom = {'abilities': {0: 'Early Bird', 1: 'Flash Fire', 'H': 'Unnerve'}}
    Houndoommega = {'abilities': {0: 'Solar Power'}}
    Kingdra = {'abilities': {0: 'Swift Swim', 1: 'Sniper', 'H': 'Damp'}}
    Phanpy = {'abilities': {0: 'Pickup', 'H': 'Sand Veil'}}
    Donphan = {'abilities': {0: 'Sturdy', 'H': 'Sand Veil'}}
    Stantler = {'abilities': {0: 'Intimidate', 1: 'Frisk', 'H': 'Sap Sipper'}}
    Smeargle = {'abilities': {0: 'Own Tempo', 1: 'Technician', 'H': 'Moody'}}
    Tyrogue = {'abilities': {0: 'Guts', 1: 'Steadfast', 'H': 'Vital Spirit'}}
    Hitmontop = {'abilities': {0: 'Intimidate', 1: 'Technician', 'H': 'Steadfast'}}
    Smoochum = {'abilities': {0: 'Oblivious', 1: 'Forewarn', 'H': 'Hydration'}}
    Elekid = {'abilities': {0: 'Static', 'H': 'Vital Spirit'}}
    Magby = {'abilities': {0: 'Flame Body', 'H': 'Vital Spirit'}}
    Miltank = {'abilities': {0: 'Thick Fat', 1: 'Scrappy', 'H': 'Sap Sipper'}}
    Blissey = {'abilities': {0: 'Natural Cure', 1: 'Serene Grace', 'H': 'Healer'}}
    Raikou = {'abilities': {0: 'Pressure', 'H': 'Inner Focus'}}
    Entei = {'abilities': {0: 'Pressure', 'H': 'Inner Focus'}}
    Suicune = {'abilities': {0: 'Pressure', 'H': 'Inner Focus'}}
    Larvitar = {'abilities': {0: 'Guts', 'H': 'Sand Veil'}}
    Pupitar = {'abilities': {0: 'Shed Skin'}}
    Tyranitar = {'abilities': {0: 'Sand Stream', 'H': 'Unnerve'}}
    Tyranitarmega = {'abilities': {0: 'Sand Stream'}}
    Lugia = {'abilities': {0: 'Pressure', 'H': 'Multiscale'}}
    Hooh = {'abilities': {0: 'Pressure', 'H': 'Regenerator'}}
    Celebi = {'abilities': {0: 'Natural Cure'}}
    Treecko = {'abilities': {0: 'Overgrow', 'H': 'Unburden'}}
    Grovyle = {'abilities': {0: 'Overgrow', 'H': 'Unburden'}}
    Sceptile = {'abilities': {0: 'Overgrow', 'H': 'Unburden'}}
    Sceptilemega = {'abilities': {0: 'Lightning Rod'}}
    Torchic = {'abilities': {0: 'Blaze', 'H': 'Speed Boost'}}
    Combusken = {'abilities': {0: 'Blaze', 'H': 'Speed Boost'}}
    Blaziken = {'abilities': {0: 'Blaze', 'H': 'Speed Boost'}}
    Blazikenmega = {'abilities': {0: 'Speed Boost'}}
    Mudkip = {'abilities': {0: 'Torrent', 'H': 'Damp'}}
    Marshtomp = {'abilities': {0: 'Torrent', 'H': 'Damp'}}
    Swampert = {'abilities': {0: 'Torrent', 'H': 'Damp'}}
    Swampertmega = {'abilities': {0: 'Swift Swim'}}
    Poochyena = {'abilities': {0: 'Run Away', 1: 'Quick Feet', 'H': 'Rattled'}}
    Mightyena = {'abilities': {0: 'Intimidate', 1: 'Quick Feet', 'H': 'Moxie'}}
    Zigzagoon = {'abilities': {0: 'Pickup', 1: 'Gluttony', 'H': 'Quick Feet'}}
    Zigzagoongalar = {'abilities': {0: 'Pickup', 1: 'Gluttony', 'H': 'Quick Feet'}}
    Linoone = {'abilities': {0: 'Pickup', 1: 'Gluttony', 'H': 'Quick Feet'}}
    Linoonegalar = {'abilities': {0: 'Pickup', 1: 'Gluttony', 'H': 'Quick Feet'}}
    Wurmple = {'abilities': {0: 'Shield Dust', 'H': 'Run Away'}}
    Silcoon = {'abilities': {0: 'Shed Skin'}}
    Beautifly = {'abilities': {0: 'Swarm', 'H': 'Rivalry'}}
    Cascoon = {'abilities': {0: 'Shed Skin'}}
    Dustox = {'abilities': {0: 'Shield Dust', 'H': 'Compound Eyes'}}
    Lotad = {'abilities': {0: 'Swift Swim', 1: 'Rain Dish', 'H': 'Own Tempo'}}
    Lombre = {'abilities': {0: 'Swift Swim', 1: 'Rain Dish', 'H': 'Own Tempo'}}
    Ludicolo = {'abilities': {0: 'Swift Swim', 1: 'Rain Dish', 'H': 'Own Tempo'}}
    Seedot = {'abilities': {0: 'Chlorophyll', 1: 'Early Bird', 'H': 'Pickpocket'}}
    Nuzleaf = {'abilities': {0: 'Chlorophyll', 1: 'Early Bird', 'H': 'Pickpocket'}}
    Shiftry = {'abilities': {0: 'Chlorophyll', 1: 'Early Bird', 'H': 'Pickpocket'}}
    Taillow = {'abilities': {0: 'Guts', 'H': 'Scrappy'}}
    Swellow = {'abilities': {0: 'Guts', 'H': 'Scrappy'}}
    Wingull = {'abilities': {0: 'Keen Eye', 1: 'Hydration', 'H': 'Rain Dish'}}
    Pelipper = {'abilities': {0: 'Keen Eye', 1: 'Drizzle', 'H': 'Rain Dish'}}
    Ralts = {'abilities': {0: 'Synchronize', 1: 'Trace', 'H': 'Telepathy'}}
    Kirlia = {'abilities': {0: 'Synchronize', 1: 'Trace', 'H': 'Telepathy'}}
    Gardevoir = {'abilities': {0: 'Synchronize', 1: 'Trace', 'H': 'Telepathy'}}
    Gardevoirmega = {'abilities': {0: 'Pixilate'}}
    Surskit = {'abilities': {0: 'Swift Swim', 'H': 'Rain Dish'}}
    Masquerain = {'abilities': {0: 'Intimidate', 'H': 'Unnerve'}}
    Shroomish = {'abilities': {0: 'Effect Spore', 1: 'Poison Heal', 'H': 'Quick Feet'}}
    Breloom = {'abilities': {0: 'Effect Spore', 1: 'Poison Heal', 'H': 'Technician'}}
    Slakoth = {'abilities': {0: 'Truant'}}
    Vigoroth = {'abilities': {0: 'Vital Spirit'}}
    Slaking = {'abilities': {0: 'Truant'}}
    Nincada = {'abilities': {0: 'Compound Eyes', 'H': 'Run Away'}}
    Ninjask = {'abilities': {0: 'Speed Boost', 'H': 'Infiltrator'}}
    Shedinja = {'abilities': {0: 'Wonder Guard'}}
    Whismur = {'abilities': {0: 'Soundproof', 'H': 'Rattled'}}
    Loudred = {'abilities': {0: 'Soundproof', 'H': 'Scrappy'}}
    Exploud = {'abilities': {0: 'Soundproof', 'H': 'Scrappy'}}
    Makuhita = {'abilities': {0: 'Thick Fat', 1: 'Guts', 'H': 'Sheer Force'}}
    Hariyama = {'abilities': {0: 'Thick Fat', 1: 'Guts', 'H': 'Sheer Force'}}
    Azurill = {'abilities': {0: 'Thick Fat', 1: 'Huge Power', 'H': 'Sap Sipper'}}
    Nosepass = {'abilities': {0: 'Sturdy', 1: 'Magnet Pull', 'H': 'Sand Force'}}
    Skitty = {'abilities': {0: 'Cute Charm', 1: 'Normalize', 'H': 'Wonder Skin'}}
    Delcatty = {'abilities': {0: 'Cute Charm', 1: 'Normalize', 'H': 'Wonder Skin'}}
    Sableye = {'abilities': {0: 'Keen Eye', 1: 'Stall', 'H': 'Prankster'}}
    Sableyemega = {'abilities': {0: 'Magic Bounce'}}
    Mawile = {'abilities': {0: 'Hyper Cutter', 1: 'Intimidate', 'H': 'Sheer Force'}}
    Mawilemega = {'abilities': {0: 'Huge Power'}}
    Aron = {'abilities': {0: 'Sturdy', 1: 'Rock Head', 'H': 'Heavy Metal'}}
    Lairon = {'abilities': {0: 'Sturdy', 1: 'Rock Head', 'H': 'Heavy Metal'}}
    Aggron = {'abilities': {0: 'Sturdy', 1: 'Rock Head', 'H': 'Heavy Metal'}}
    Aggronmega = {'abilities': {0: 'Filter'}}
    Meditite = {'abilities': {0: 'Pure Power', 'H': 'Telepathy'}}
    Medicham = {'abilities': {0: 'Pure Power', 'H': 'Telepathy'}}
    Medichammega = {'abilities': {0: 'Pure Power'}}
    Electrike = {'abilities': {0: 'Static', 1: 'Lightning Rod', 'H': 'Minus'}}
    Manectric = {'abilities': {0: 'Static', 1: 'Lightning Rod', 'H': 'Minus'}}
    Manectricmega = {'abilities': {0: 'Intimidate'}}
    Plusle = {'abilities': {0: 'Plus', 'H': 'Lightning Rod'}}
    Minun = {'abilities': {0: 'Minus', 'H': 'Volt Absorb'}}
    Volbeat = {'abilities': {0: 'Illuminate', 1: 'Swarm', 'H': 'Prankster'}}
    Illumise = {'abilities': {0: 'Oblivious', 1: 'Tinted Lens', 'H': 'Prankster'}}
    Roselia = {'abilities': {0: 'Natural Cure', 1: 'Poison Point', 'H': 'Leaf Guard'}}
    Gulpin = {'abilities': {0: 'Liquid Ooze', 1: 'Sticky Hold', 'H': 'Gluttony'}}
    Swalot = {'abilities': {0: 'Liquid Ooze', 1: 'Sticky Hold', 'H': 'Gluttony'}}
    Carvanha = {'abilities': {0: 'Rough Skin', 'H': 'Speed Boost'}}
    Sharpedo = {'abilities': {0: 'Rough Skin', 'H': 'Speed Boost'}}
    Sharpedomega = {'abilities': {0: 'Strong Jaw'}}
    Wailmer = {'abilities': {0: 'Water Veil', 1: 'Oblivious', 'H': 'Pressure'}}
    Wailord = {'abilities': {0: 'Water Veil', 1: 'Oblivious', 'H': 'Pressure'}}
    Numel = {'abilities': {0: 'Oblivious', 1: 'Simple', 'H': 'Own Tempo'}}
    Camerupt = {'abilities': {0: 'Magma Armor', 1: 'Solid Rock', 'H': 'Anger Point'}}
    Cameruptmega = {'abilities': {0: 'Sheer Force'}}
    Torkoal = {'abilities': {0: 'White Smoke', 1: 'Drought', 'H': 'Shell Armor'}}
    Spoink = {'abilities': {0: 'Thick Fat', 1: 'Own Tempo', 'H': 'Gluttony'}}
    Grumpig = {'abilities': {0: 'Thick Fat', 1: 'Own Tempo', 'H': 'Gluttony'}}
    Spinda = {'abilities': {0: 'Own Tempo', 1: 'Tangled Feet', 'H': 'Contrary'}}
    Trapinch = {'abilities': {0: 'Hyper Cutter', 1: 'Arena Trap', 'H': 'Sheer Force'}}
    Vibrava = {'abilities': {0: 'Levitate'}}
    Flygon = {'abilities': {0: 'Levitate'}}
    Cacnea = {'abilities': {0: 'Sand Veil', 'H': 'Water Absorb'}}
    Cacturne = {'abilities': {0: 'Sand Veil', 'H': 'Water Absorb'}}
    Swablu = {'abilities': {0: 'Natural Cure', 'H': 'Cloud Nine'}}
    Altaria = {'abilities': {0: 'Natural Cure', 'H': 'Cloud Nine'}}
    Altariamega = {'abilities': {0: 'Pixilate'}}
    Zangoose = {'abilities': {0: 'Immunity', 'H': 'Toxic Boost'}}
    Seviper = {'abilities': {0: 'Shed Skin', 'H': 'Infiltrator'}}
    Lunatone = {'abilities': {0: 'Levitate'}}
    Solrock = {'abilities': {0: 'Levitate'}}
    Barboach = {'abilities': {0: 'Oblivious', 1: 'Anticipation', 'H': 'Hydration'}}
    Whiscash = {'abilities': {0: 'Oblivious', 1: 'Anticipation', 'H': 'Hydration'}}
    Corphish = {'abilities': {0: 'Hyper Cutter', 1: 'Shell Armor', 'H': 'Adaptability'}}
    Crawdaunt = {'abilities': {0: 'Hyper Cutter', 1: 'Shell Armor', 'H': 'Adaptability'}}
    Baltoy = {'abilities': {0: 'Levitate'}}
    Claydol = {'abilities': {0: 'Levitate'}}
    Lileep = {'abilities': {0: 'Suction Cups', 'H': 'Storm Drain'}}
    Cradily = {'abilities': {0: 'Suction Cups', 'H': 'Storm Drain'}}
    Anorith = {'abilities': {0: 'Battle Armor', 'H': 'Swift Swim'}}
    Armaldo = {'abilities': {0: 'Battle Armor', 'H': 'Swift Swim'}}
    Feebas = {'abilities': {0: 'Swift Swim', 1: 'Oblivious', 'H': 'Adaptability'}}
    Milotic = {'abilities': {0: 'Marvel Scale', 1: 'Competitive', 'H': 'Cute Charm'}}
    Castform = {'abilities': {0: 'Forecast'}}
    Castformsunny = {'abilities': {0: 'Forecast'}}
    Castformrainy = {'abilities': {0: 'Forecast'}}
    Castformsnowy = {'abilities': {0: 'Forecast'}}
    Kecleon = {'abilities': {0: 'Color Change', 'H': 'Protean'}}
    Shuppet = {'abilities': {0: 'Insomnia', 1: 'Frisk', 'H': 'Cursed Body'}}
    Banette = {'abilities': {0: 'Insomnia', 1: 'Frisk', 'H': 'Cursed Body'}}
    Banettemega = {'abilities': {0: 'Prankster'}}
    Duskull = {'abilities': {0: 'Levitate', 'H': 'Frisk'}}
    Dusclops = {'abilities': {0: 'Pressure', 'H': 'Frisk'}}
    Tropius = {'abilities': {0: 'Chlorophyll', 1: 'Solar Power', 'H': 'Harvest'}}
    Chimecho = {'abilities': {0: 'Levitate'}}
    Absol = {'abilities': {0: 'Pressure', 1: 'Super Luck', 'H': 'Justified'}}
    Absolmega = {'abilities': {0: 'Magic Bounce'}}
    Wynaut = {'abilities': {0: 'Shadow Tag', 'H': 'Telepathy'}}
    Snorunt = {'abilities': {0: 'Inner Focus', 1: 'Ice Body', 'H': 'Moody'}}
    Glalie = {'abilities': {0: 'Inner Focus', 1: 'Ice Body', 'H': 'Moody'}}
    Glaliemega = {'abilities': {0: 'Refrigerate'}}
    Spheal = {'abilities': {0: 'Thick Fat', 1: 'Ice Body', 'H': 'Oblivious'}}
    Sealeo = {'abilities': {0: 'Thick Fat', 1: 'Ice Body', 'H': 'Oblivious'}}
    Walrein = {'abilities': {0: 'Thick Fat', 1: 'Ice Body', 'H': 'Oblivious'}}
    Clamperl = {'abilities': {0: 'Shell Armor', 'H': 'Rattled'}}
    Huntail = {'abilities': {0: 'Swift Swim', 'H': 'Water Veil'}}
    Gorebyss = {'abilities': {0: 'Swift Swim', 'H': 'Hydration'}}
    Relicanth = {'abilities': {0: 'Swift Swim', 1: 'Rock Head', 'H': 'Sturdy'}}
    Luvdisc = {'abilities': {0: 'Swift Swim', 'H': 'Hydration'}}
    Bagon = {'abilities': {0: 'Rock Head', 'H': 'Sheer Force'}}
    Shelgon = {'abilities': {0: 'Rock Head', 'H': 'Overcoat'}}
    Salamence = {'abilities': {0: 'Intimidate', 'H': 'Moxie'}}
    Salamencemega = {'abilities': {0: 'Aerilate'}}
    Beldum = {'abilities': {0: 'Clear Body', 'H': 'Light Metal'}}
    Metang = {'abilities': {0: 'Clear Body', 'H': 'Light Metal'}}
    Metagross = {'abilities': {0: 'Clear Body', 'H': 'Light Metal'}}
    Metagrossmega = {'abilities': {0: 'Tough Claws'}}
    Regirock = {'abilities': {0: 'Clear Body', 'H': 'Sturdy'}}
    Regice = {'abilities': {0: 'Clear Body', 'H': 'Ice Body'}}
    Registeel = {'abilities': {0: 'Clear Body', 'H': 'Light Metal'}}
    Latias = {'abilities': {0: 'Levitate'}}
    Latiasmega = {'abilities': {0: 'Levitate'}}
    Latios = {'abilities': {0: 'Levitate'}}
    Latiosmega = {'abilities': {0: 'Levitate'}}
    Kyogre = {'abilities': {0: 'Drizzle'}}
    Kyogreprimal = {'abilities': {0: 'Primordial Sea'}}
    Groudon = {'abilities': {0: 'Drought'}}
    Groudonprimal = {'abilities': {0: 'Desolate Land'}}
    Rayquaza = {'abilities': {0: 'Air Lock'}}
    Rayquazamega = {'abilities': {0: 'Delta Stream'}}
    Jirachi = {'abilities': {0: 'Serene Grace'}}
    Deoxys = {'abilities': {0: 'Pressure'}}
    Deoxysattack = {'abilities': {0: 'Pressure'}}
    Deoxysdefense = {'abilities': {0: 'Pressure'}}
    Deoxysspeed = {'abilities': {0: 'Pressure'}}
    Turtwig = {'abilities': {0: 'Overgrow', 'H': 'Shell Armor'}}
    Grotle = {'abilities': {0: 'Overgrow', 'H': 'Shell Armor'}}
    Torterra = {'abilities': {0: 'Overgrow', 'H': 'Shell Armor'}}
    Chimchar = {'abilities': {0: 'Blaze', 'H': 'Iron Fist'}}
    Monferno = {'abilities': {0: 'Blaze', 'H': 'Iron Fist'}}
    Infernape = {'abilities': {0: 'Blaze', 'H': 'Iron Fist'}}
    Piplup = {'abilities': {0: 'Torrent', 'H': 'Defiant'}}
    Prinplup = {'abilities': {0: 'Torrent', 'H': 'Defiant'}}
    Empoleon = {'abilities': {0: 'Torrent', 'H': 'Defiant'}}
    Starly = {'abilities': {0: 'Keen Eye', 'H': 'Reckless'}}
    Staravia = {'abilities': {0: 'Intimidate', 'H': 'Reckless'}}
    Staraptor = {'abilities': {0: 'Intimidate', 'H': 'Reckless'}}
    Bidoof = {'abilities': {0: 'Simple', 1: 'Unaware', 'H': 'Moody'}}
    Bibarel = {'abilities': {0: 'Simple', 1: 'Unaware', 'H': 'Moody'}}
    Kricketot = {'abilities': {0: 'Shed Skin', 'H': 'Run Away'}}
    Kricketune = {'abilities': {0: 'Swarm', 'H': 'Technician'}}
    Shinx = {'abilities': {0: 'Rivalry', 1: 'Intimidate', 'H': 'Guts'}}
    Luxio = {'abilities': {0: 'Rivalry', 1: 'Intimidate', 'H': 'Guts'}}
    Luxray = {'abilities': {0: 'Rivalry', 1: 'Intimidate', 'H': 'Guts'}}
    Budew = {'abilities': {0: 'Natural Cure', 1: 'Poison Point', 'H': 'Leaf Guard'}}
    Roserade = {'abilities': {0: 'Natural Cure', 1: 'Poison Point', 'H': 'Technician'}}
    Cranidos = {'abilities': {0: 'Mold Breaker', 'H': 'Sheer Force'}}
    Rampardos = {'abilities': {0: 'Mold Breaker', 'H': 'Sheer Force'}}
    Shieldon = {'abilities': {0: 'Sturdy', 'H': 'Soundproof'}}
    Bastiodon = {'abilities': {0: 'Sturdy', 'H': 'Soundproof'}}
    Burmy = {'abilities': {0: 'Shed Skin', 'H': 'Overcoat'}}
    Wormadam = {'abilities': {0: 'Anticipation', 'H': 'Overcoat'}}
    Wormadamsandy = {'abilities': {0: 'Anticipation', 'H': 'Overcoat'}}
    Wormadamtrash = {'abilities': {0: 'Anticipation', 'H': 'Overcoat'}}
    Mothim = {'abilities': {0: 'Swarm', 'H': 'Tinted Lens'}}
    Combee = {'abilities': {0: 'Honey Gather', 'H': 'Hustle'}}
    Vespiquen = {'abilities': {0: 'Pressure', 'H': 'Unnerve'}}
    Pachirisu = {'abilities': {0: 'Run Away', 1: 'Pickup', 'H': 'Volt Absorb'}}
    Buizel = {'abilities': {0: 'Swift Swim', 'H': 'Water Veil'}}
    Floatzel = {'abilities': {0: 'Swift Swim', 'H': 'Water Veil'}}
    Cherubi = {'abilities': {0: 'Chlorophyll'}}
    Cherrim = {'abilities': {0: 'Flower Gift'}}
    Cherrimsunshine = {'abilities': {0: 'Flower Gift'}}
    Shellos = {'abilities': {0: 'Sticky Hold', 1: 'Storm Drain', 'H': 'Sand Force'}}
    Gastrodon = {'abilities': {0: 'Sticky Hold', 1: 'Storm Drain', 'H': 'Sand Force'}}
    Ambipom = {'abilities': {0: 'Technician', 1: 'Pickup', 'H': 'Skill Link'}}
    Drifloon = {'abilities': {0: 'Aftermath', 1: 'Unburden', 'H': 'Flare Boost'}}
    Drifblim = {'abilities': {0: 'Aftermath', 1: 'Unburden', 'H': 'Flare Boost'}}
    Buneary = {'abilities': {0: 'Run Away', 1: 'Klutz', 'H': 'Limber'}}
    Lopunny = {'abilities': {0: 'Cute Charm', 1: 'Klutz', 'H': 'Limber'}}
    Lopunnymega = {'abilities': {0: 'Scrappy'}}
    Mismagius = {'abilities': {0: 'Levitate'}}
    Honchkrow = {'abilities': {0: 'Insomnia', 1: 'Super Luck', 'H': 'Moxie'}}
    Glameow = {'abilities': {0: 'Limber', 1: 'Own Tempo', 'H': 'Keen Eye'}}
    Purugly = {'abilities': {0: 'Thick Fat', 1: 'Own Tempo', 'H': 'Defiant'}}
    Chingling = {'abilities': {0: 'Levitate'}}
    Stunky = {'abilities': {0: 'Stench', 1: 'Aftermath', 'H': 'Keen Eye'}}
    Skuntank = {'abilities': {0: 'Stench', 1: 'Aftermath', 'H': 'Keen Eye'}}
    Bronzor = {'abilities': {0: 'Levitate', 1: 'Heatproof', 'H': 'Heavy Metal'}}
    Bronzong = {'abilities': {0: 'Levitate', 1: 'Heatproof', 'H': 'Heavy Metal'}}
    Bonsly = {'abilities': {0: 'Sturdy', 1: 'Rock Head', 'H': 'Rattled'}}
    Mimejr = {'abilities': {0: 'Soundproof', 1: 'Filter', 'H': 'Technician'}}
    Happiny = {'abilities': {0: 'Natural Cure', 1: 'Serene Grace', 'H': 'Friend Guard'}}
    Chatot = {'abilities': {0: 'Keen Eye', 1: 'Tangled Feet', 'H': 'Big Pecks'}}
    Spiritomb = {'abilities': {0: 'Pressure', 'H': 'Infiltrator'}}
    Gible = {'abilities': {0: 'Sand Veil', 'H': 'Rough Skin'}}
    Gabite = {'abilities': {0: 'Sand Veil', 'H': 'Rough Skin'}}
    Garchomp = {'abilities': {0: 'Sand Veil', 'H': 'Rough Skin'}}
    Garchompmega = {'abilities': {0: 'Sand Force'}}
    Munchlax = {'abilities': {0: 'Pickup', 1: 'Thick Fat', 'H': 'Gluttony'}}
    Riolu = {'abilities': {0: 'Steadfast', 1: 'Inner Focus', 'H': 'Prankster'}}
    Lucario = {'abilities': {0: 'Steadfast', 1: 'Inner Focus', 'H': 'Justified'}}
    Lucariomega = {'abilities': {0: 'Adaptability'}}
    Hippopotas = {'abilities': {0: 'Sand Stream', 'H': 'Sand Force'}}
    Hippowdon = {'abilities': {0: 'Sand Stream', 'H': 'Sand Force'}}
    Skorupi = {'abilities': {0: 'Battle Armor', 1: 'Sniper', 'H': 'Keen Eye'}}
    Drapion = {'abilities': {0: 'Battle Armor', 1: 'Sniper', 'H': 'Keen Eye'}}
    Croagunk = {'abilities': {0: 'Anticipation', 1: 'Dry Skin', 'H': 'Poison Touch'}}
    Toxicroak = {'abilities': {0: 'Anticipation', 1: 'Dry Skin', 'H': 'Poison Touch'}}
    Carnivine = {'abilities': {0: 'Levitate'}}
    Finneon = {'abilities': {0: 'Swift Swim', 1: 'Storm Drain', 'H': 'Water Veil'}}
    Lumineon = {'abilities': {0: 'Swift Swim', 1: 'Storm Drain', 'H': 'Water Veil'}}
    Mantyke = {'abilities': {0: 'Swift Swim', 1: 'Water Absorb', 'H': 'Water Veil'}}
    Snover = {'abilities': {0: 'Snow Warning', 'H': 'Soundproof'}}
    Abomasnow = {'abilities': {0: 'Snow Warning', 'H': 'Soundproof'}}
    Abomasnowmega = {'abilities': {0: 'Snow Warning'}}
    Weavile = {'abilities': {0: 'Pressure', 'H': 'Pickpocket'}}
    Magnezone = {'abilities': {0: 'Magnet Pull', 1: 'Sturdy', 'H': 'Analytic'}}
    Lickilicky = {'abilities': {0: 'Own Tempo', 1: 'Oblivious', 'H': 'Cloud Nine'}}
    Rhyperior = {'abilities': {0: 'Lightning Rod', 1: 'Solid Rock', 'H': 'Reckless'}}
    Tangrowth = {'abilities': {0: 'Chlorophyll', 1: 'Leaf Guard', 'H': 'Regenerator'}}
    Electivire = {'abilities': {0: 'Motor Drive', 'H': 'Vital Spirit'}}
    Magmortar = {'abilities': {0: 'Flame Body', 'H': 'Vital Spirit'}}
    Togekiss = {'abilities': {0: 'Hustle', 1: 'Serene Grace', 'H': 'Super Luck'}}
    Yanmega = {'abilities': {0: 'Speed Boost', 1: 'Tinted Lens', 'H': 'Frisk'}}
    Leafeon = {'abilities': {0: 'Leaf Guard', 'H': 'Chlorophyll'}}
    Glaceon = {'abilities': {0: 'Snow Cloak', 'H': 'Ice Body'}}
    Gliscor = {'abilities': {0: 'Hyper Cutter', 1: 'Sand Veil', 'H': 'Poison Heal'}}
    Mamoswine = {'abilities': {0: 'Oblivious', 1: 'Snow Cloak', 'H': 'Thick Fat'}}
    Porygonz = {'abilities': {0: 'Adaptability', 1: 'Download', 'H': 'Analytic'}}
    Gallade = {'abilities': {0: 'Steadfast', 'H': 'Justified'}}
    Gallademega = {'abilities': {0: 'Inner Focus'}}
    Probopass = {'abilities': {0: 'Sturdy', 1: 'Magnet Pull', 'H': 'Sand Force'}}
    Dusknoir = {'abilities': {0: 'Pressure', 'H': 'Frisk'}}
    Froslass = {'abilities': {0: 'Snow Cloak', 'H': 'Cursed Body'}}
    Rotom = {'abilities': {0: 'Levitate'}}
    Rotomheat = {'abilities': {0: 'Levitate'}}
    Rotomwash = {'abilities': {0: 'Levitate'}}
    Rotomfrost = {'abilities': {0: 'Levitate'}}
    Rotomfan = {'abilities': {0: 'Levitate'}}
    Rotommow = {'abilities': {0: 'Levitate'}}
    Uxie = {'abilities': {0: 'Levitate'}}
    Mesprit = {'abilities': {0: 'Levitate'}}
    Azelf = {'abilities': {0: 'Levitate'}}
    Dialga = {'abilities': {0: 'Pressure', 'H': 'Telepathy'}}
    Palkia = {'abilities': {0: 'Pressure', 'H': 'Telepathy'}}
    Heatran = {'abilities': {0: 'Flash Fire', 'H': 'Flame Body'}}
    Regigigas = {'abilities': {0: 'Slow Start'}}
    Giratina = {'abilities': {0: 'Pressure', 'H': 'Telepathy'}}
    Giratinaorigin = {'abilities': {0: 'Levitate'}}
    Cresselia = {'abilities': {0: 'Levitate'}}
    Phione = {'abilities': {0: 'Hydration'}}
    Manaphy = {'abilities': {0: 'Hydration'}}
    Darkrai = {'abilities': {0: 'Bad Dreams'}}
    Shaymin = {'abilities': {0: 'Natural Cure'}}
    Shayminsky = {'abilities': {0: 'Serene Grace'}}
    Arceus = {'abilities': {0: 'Multitype'}}
    Arceusbug = {'abilities': {0: 'Multitype'}}
    Arceusdark = {'abilities': {0: 'Multitype'}}
    Arceusdragon = {'abilities': {0: 'Multitype'}}
    Arceuselectric = {'abilities': {0: 'Multitype'}}
    Arceusfairy = {'abilities': {0: 'Multitype'}}
    Arceusfighting = {'abilities': {0: 'Multitype'}}
    Arceusfire = {'abilities': {0: 'Multitype'}}
    Arceusflying = {'abilities': {0: 'Multitype'}}
    Arceusghost = {'abilities': {0: 'Multitype'}}
    Arceusgrass = {'abilities': {0: 'Multitype'}}
    Arceusground = {'abilities': {0: 'Multitype'}}
    Arceusice = {'abilities': {0: 'Multitype'}}
    Arceuspoison = {'abilities': {0: 'Multitype'}}
    Arceuspsychic = {'abilities': {0: 'Multitype'}}
    Arceusrock = {'abilities': {0: 'Multitype'}}
    Arceussteel = {'abilities': {0: 'Multitype'}}
    Arceuswater = {'abilities': {0: 'Multitype'}}
    Victini = {'abilities': {0: 'Victory Star'}}
    Snivy = {'abilities': {0: 'Overgrow', 'H': 'Contrary'}}
    Servine = {'abilities': {0: 'Overgrow', 'H': 'Contrary'}}
    Serperior = {'abilities': {0: 'Overgrow', 'H': 'Contrary'}}
    Tepig = {'abilities': {0: 'Blaze', 'H': 'Thick Fat'}}
    Pignite = {'abilities': {0: 'Blaze', 'H': 'Thick Fat'}}
    Emboar = {'abilities': {0: 'Blaze', 'H': 'Reckless'}}
    Oshawott = {'abilities': {0: 'Torrent', 'H': 'Shell Armor'}}
    Dewott = {'abilities': {0: 'Torrent', 'H': 'Shell Armor'}}
    Samurott = {'abilities': {0: 'Torrent', 'H': 'Shell Armor'}}
    Patrat = {'abilities': {0: 'Run Away', 1: 'Keen Eye', 'H': 'Analytic'}}
    Watchog = {'abilities': {0: 'Illuminate', 1: 'Keen Eye', 'H': 'Analytic'}}
    Lillipup = {'abilities': {0: 'Vital Spirit', 1: 'Pickup', 'H': 'Run Away'}}
    Herdier = {'abilities': {0: 'Intimidate', 1: 'Sand Rush', 'H': 'Scrappy'}}
    Stoutland = {'abilities': {0: 'Intimidate', 1: 'Sand Rush', 'H': 'Scrappy'}}
    Purrloin = {'abilities': {0: 'Limber', 1: 'Unburden', 'H': 'Prankster'}}
    Liepard = {'abilities': {0: 'Limber', 1: 'Unburden', 'H': 'Prankster'}}
    Pansage = {'abilities': {0: 'Gluttony', 'H': 'Overgrow'}}
    Simisage = {'abilities': {0: 'Gluttony', 'H': 'Overgrow'}}
    Pansear = {'abilities': {0: 'Gluttony', 'H': 'Blaze'}}
    Simisear = {'abilities': {0: 'Gluttony', 'H': 'Blaze'}}
    Panpour = {'abilities': {0: 'Gluttony', 'H': 'Torrent'}}
    Simipour = {'abilities': {0: 'Gluttony', 'H': 'Torrent'}}
    Munna = {'abilities': {0: 'Forewarn', 1: 'Synchronize', 'H': 'Telepathy'}}
    Musharna = {'abilities': {0: 'Forewarn', 1: 'Synchronize', 'H': 'Telepathy'}}
    Pidove = {'abilities': {0: 'Big Pecks', 1: 'Super Luck', 'H': 'Rivalry'}}
    Tranquill = {'abilities': {0: 'Big Pecks', 1: 'Super Luck', 'H': 'Rivalry'}}
    Unfezant = {'abilities': {0: 'Big Pecks', 1: 'Super Luck', 'H': 'Rivalry'}}
    Blitzle = {'abilities': {0: 'Lightning Rod', 1: 'Motor Drive', 'H': 'Sap Sipper'}}
    Zebstrika = {'abilities': {0: 'Lightning Rod', 1: 'Motor Drive', 'H': 'Sap Sipper'}}
    Roggenrola = {'abilities': {0: 'Sturdy', 1: 'Weak Armor', 'H': 'Sand Force'}}
    Boldore = {'abilities': {0: 'Sturdy', 1: 'Weak Armor', 'H': 'Sand Force'}}
    Gigalith = {'abilities': {0: 'Sturdy', 1: 'Sand Stream', 'H': 'Sand Force'}}
    Woobat = {'abilities': {0: 'Unaware', 1: 'Klutz', 'H': 'Simple'}}
    Swoobat = {'abilities': {0: 'Unaware', 1: 'Klutz', 'H': 'Simple'}}
    Drilbur = {'abilities': {0: 'Sand Rush', 1: 'Sand Force', 'H': 'Mold Breaker'}}
    Excadrill = {'abilities': {0: 'Sand Rush', 1: 'Sand Force', 'H': 'Mold Breaker'}}
    Audino = {'abilities': {0: 'Healer', 1: 'Regenerator', 'H': 'Klutz'}}
    Audinomega = {'abilities': {0: 'Healer'}}
    Timburr = {'abilities': {0: 'Guts', 1: 'Sheer Force', 'H': 'Iron Fist'}}
    Gurdurr = {'abilities': {0: 'Guts', 1: 'Sheer Force', 'H': 'Iron Fist'}}
    Conkeldurr = {'abilities': {0: 'Guts', 1: 'Sheer Force', 'H': 'Iron Fist'}}
    Tympole = {'abilities': {0: 'Swift Swim', 1: 'Hydration', 'H': 'Water Absorb'}}
    Palpitoad = {'abilities': {0: 'Swift Swim', 1: 'Hydration', 'H': 'Water Absorb'}}
    Seismitoad = {'abilities': {0: 'Swift Swim', 1: 'Poison Touch', 'H': 'Water Absorb'}}
    Throh = {'abilities': {0: 'Guts', 1: 'Inner Focus', 'H': 'Mold Breaker'}}
    Sawk = {'abilities': {0: 'Sturdy', 1: 'Inner Focus', 'H': 'Mold Breaker'}}
    Sewaddle = {'abilities': {0: 'Swarm', 1: 'Chlorophyll', 'H': 'Overcoat'}}
    Swadloon = {'abilities': {0: 'Leaf Guard', 1: 'Chlorophyll', 'H': 'Overcoat'}}
    Leavanny = {'abilities': {0: 'Swarm', 1: 'Chlorophyll', 'H': 'Overcoat'}}
    Venipede = {'abilities': {0: 'Poison Point', 1: 'Swarm', 'H': 'Speed Boost'}}
    Whirlipede = {'abilities': {0: 'Poison Point', 1: 'Swarm', 'H': 'Speed Boost'}}
    Scolipede = {'abilities': {0: 'Poison Point', 1: 'Swarm', 'H': 'Speed Boost'}}
    Cottonee = {'abilities': {0: 'Prankster', 1: 'Infiltrator', 'H': 'Chlorophyll'}}
    Whimsicott = {'abilities': {0: 'Prankster', 1: 'Infiltrator', 'H': 'Chlorophyll'}}
    Petilil = {'abilities': {0: 'Chlorophyll', 1: 'Own Tempo', 'H': 'Leaf Guard'}}
    Lilligant = {'abilities': {0: 'Chlorophyll', 1: 'Own Tempo', 'H': 'Leaf Guard'}}
    Basculin = {'abilities': {0: 'Reckless', 1: 'Adaptability', 'H': 'Mold Breaker'}}
    Basculinbluestriped = {'abilities': {0: 'Rock Head', 1: 'Adaptability', 'H': 'Mold Breaker'}}
    Sandile = {'abilities': {0: 'Intimidate', 1: 'Moxie', 'H': 'Anger Point'}}
    Krokorok = {'abilities': {0: 'Intimidate', 1: 'Moxie', 'H': 'Anger Point'}}
    Krookodile = {'abilities': {0: 'Intimidate', 1: 'Moxie', 'H': 'Anger Point'}}
    Darumaka = {'abilities': {0: 'Hustle', 'H': 'Inner Focus'}}
    Darumakagalar = {'abilities': {0: 'Hustle', 'H': 'Inner Focus'}}
    Darmanitan = {'abilities': {0: 'Sheer Force', 'H': 'Zen Mode'}}
    Darmanitanzen = {'abilities': {0: 'Zen Mode'}}
    Darmanitangalar = {'abilities': {0: 'Gorilla Tactics', 'H': 'Zen Mode'}}
    Darmanitangalarzen = {'abilities': {0: 'Zen Mode'}}
    Maractus = {'abilities': {0: 'Water Absorb', 1: 'Chlorophyll', 'H': 'Storm Drain'}}
    Dwebble = {'abilities': {0: 'Sturdy', 1: 'Shell Armor', 'H': 'Weak Armor'}}
    Crustle = {'abilities': {0: 'Sturdy', 1: 'Shell Armor', 'H': 'Weak Armor'}}
    Scraggy = {'abilities': {0: 'Shed Skin', 1: 'Moxie', 'H': 'Intimidate'}}
    Scrafty = {'abilities': {0: 'Shed Skin', 1: 'Moxie', 'H': 'Intimidate'}}
    Sigilyph = {'abilities': {0: 'Wonder Skin', 1: 'Magic Guard', 'H': 'Tinted Lens'}}
    Yamask = {'abilities': {0: 'Mummy'}}
    Yamaskgalar = {'abilities': {0: 'Wandering Spirit'}}
    Cofagrigus = {'abilities': {0: 'Mummy'}}
    Tirtouga = {'abilities': {0: 'Solid Rock', 1: 'Sturdy', 'H': 'Swift Swim'}}
    Carracosta = {'abilities': {0: 'Solid Rock', 1: 'Sturdy', 'H': 'Swift Swim'}}
    Archen = {'abilities': {0: 'Defeatist'}}
    Archeops = {'abilities': {0: 'Defeatist'}}
    Trubbish = {'abilities': {0: 'Stench', 1: 'Sticky Hold', 'H': 'Aftermath'}}
    Garbodor = {'abilities': {0: 'Stench', 1: 'Weak Armor', 'H': 'Aftermath'}}
    Garbodorgmax = {'abilities': {0: 'Stench', 1: 'Weak Armor', 'H': 'Aftermath'}}
    Zorua = {'abilities': {0: 'Illusion'}}
    Zoroark = {'abilities': {0: 'Illusion'}}
    Minccino = {'abilities': {0: 'Cute Charm', 1: 'Technician', 'H': 'Skill Link'}}
    Cinccino = {'abilities': {0: 'Cute Charm', 1: 'Technician', 'H': 'Skill Link'}}
    Gothita = {'abilities': {0: 'Frisk', 1: 'Competitive', 'H': 'Shadow Tag'}}
    Gothorita = {'abilities': {0: 'Frisk', 1: 'Competitive', 'H': 'Shadow Tag'}}
    Gothitelle = {'abilities': {0: 'Frisk', 1: 'Competitive', 'H': 'Shadow Tag'}}
    Solosis = {'abilities': {0: 'Overcoat', 1: 'Magic Guard', 'H': 'Regenerator'}}
    Duosion = {'abilities': {0: 'Overcoat', 1: 'Magic Guard', 'H': 'Regenerator'}}
    Reuniclus = {'abilities': {0: 'Overcoat', 1: 'Magic Guard', 'H': 'Regenerator'}}
    Ducklett = {'abilities': {0: 'Keen Eye', 1: 'Big Pecks', 'H': 'Hydration'}}
    Swanna = {'abilities': {0: 'Keen Eye', 1: 'Big Pecks', 'H': 'Hydration'}}
    Vanillite = {'abilities': {0: 'Ice Body', 1: 'Snow Cloak', 'H': 'Weak Armor'}}
    Vanillish = {'abilities': {0: 'Ice Body', 1: 'Snow Cloak', 'H': 'Weak Armor'}}
    Vanilluxe = {'abilities': {0: 'Ice Body', 1: 'Snow Warning', 'H': 'Weak Armor'}}
    Deerling = {'abilities': {0: 'Chlorophyll', 1: 'Sap Sipper', 'H': 'Serene Grace'}}
    Sawsbuck = {'abilities': {0: 'Chlorophyll', 1: 'Sap Sipper', 'H': 'Serene Grace'}}
    Emolga = {'abilities': {0: 'Static', 'H': 'Motor Drive'}}
    Karrablast = {'abilities': {0: 'Swarm', 1: 'Shed Skin', 'H': 'No Guard'}}
    Escavalier = {'abilities': {0: 'Swarm', 1: 'Shell Armor', 'H': 'Overcoat'}}
    Foongus = {'abilities': {0: 'Effect Spore', 'H': 'Regenerator'}}
    Amoonguss = {'abilities': {0: 'Effect Spore', 'H': 'Regenerator'}}
    Frillish = {'abilities': {0: 'Water Absorb', 1: 'Cursed Body', 'H': 'Damp'}}
    Jellicent = {'abilities': {0: 'Water Absorb', 1: 'Cursed Body', 'H': 'Damp'}}
    Alomomola = {'abilities': {0: 'Healer', 1: 'Hydration', 'H': 'Regenerator'}}
    Joltik = {'abilities': {0: 'Compound Eyes', 1: 'Unnerve', 'H': 'Swarm'}}
    Galvantula = {'abilities': {0: 'Compound Eyes', 1: 'Unnerve', 'H': 'Swarm'}}
    Ferroseed = {'abilities': {0: 'Iron Barbs'}}
    Ferrothorn = {'abilities': {0: 'Iron Barbs', 'H': 'Anticipation'}}
    Klink = {'abilities': {0: 'Plus', 1: 'Minus', 'H': 'Clear Body'}}
    Klang = {'abilities': {0: 'Plus', 1: 'Minus', 'H': 'Clear Body'}}
    Klinklang = {'abilities': {0: 'Plus', 1: 'Minus', 'H': 'Clear Body'}}
    Tynamo = {'abilities': {0: 'Levitate'}}
    Eelektrik = {'abilities': {0: 'Levitate'}}
    Eelektross = {'abilities': {0: 'Levitate'}}
    Elgyem = {'abilities': {0: 'Telepathy', 1: 'Synchronize', 'H': 'Analytic'}}
    Beheeyem = {'abilities': {0: 'Telepathy', 1: 'Synchronize', 'H': 'Analytic'}}
    Litwick = {'abilities': {0: 'Flash Fire', 1: 'Flame Body', 'H': 'Infiltrator'}}
    Lampent = {'abilities': {0: 'Flash Fire', 1: 'Flame Body', 'H': 'Infiltrator'}}
    Chandelure = {'abilities': {0: 'Flash Fire', 1: 'Flame Body', 'H': 'Infiltrator'}}
    Axew = {'abilities': {0: 'Rivalry', 1: 'Mold Breaker', 'H': 'Unnerve'}}
    Fraxure = {'abilities': {0: 'Rivalry', 1: 'Mold Breaker', 'H': 'Unnerve'}}
    Haxorus = {'abilities': {0: 'Rivalry', 1: 'Mold Breaker', 'H': 'Unnerve'}}
    Cubchoo = {'abilities': {0: 'Snow Cloak', 1: 'Slush Rush', 'H': 'Rattled'}}
    Beartic = {'abilities': {0: 'Snow Cloak', 1: 'Slush Rush', 'H': 'Swift Swim'}}
    Cryogonal = {'abilities': {0: 'Levitate'}}
    Shelmet = {'abilities': {0: 'Hydration', 1: 'Shell Armor', 'H': 'Overcoat'}}
    Accelgor = {'abilities': {0: 'Hydration', 1: 'Sticky Hold', 'H': 'Unburden'}}
    Stunfisk = {'abilities': {0: 'Static', 1: 'Limber', 'H': 'Sand Veil'}}
    Stunfiskgalar = {'abilities': {0: 'Mimicry'}}
    Mienfoo = {'abilities': {0: 'Inner Focus', 1: 'Regenerator', 'H': 'Reckless'}}
    Mienshao = {'abilities': {0: 'Inner Focus', 1: 'Regenerator', 'H': 'Reckless'}}
    Druddigon = {'abilities': {0: 'Rough Skin', 1: 'Sheer Force', 'H': 'Mold Breaker'}}
    Golett = {'abilities': {0: 'Iron Fist', 1: 'Klutz', 'H': 'No Guard'}}
    Golurk = {'abilities': {0: 'Iron Fist', 1: 'Klutz', 'H': 'No Guard'}}
    Pawniard = {'abilities': {0: 'Defiant', 1: 'Inner Focus', 'H': 'Pressure'}}
    Bisharp = {'abilities': {0: 'Defiant', 1: 'Inner Focus', 'H': 'Pressure'}}
    Bouffalant = {'abilities': {0: 'Reckless', 1: 'Sap Sipper', 'H': 'Soundproof'}}
    Rufflet = {'abilities': {0: 'Keen Eye', 1: 'Sheer Force', 'H': 'Hustle'}}
    Braviary = {'abilities': {0: 'Keen Eye', 1: 'Sheer Force', 'H': 'Defiant'}}
    Vullaby = {'abilities': {0: 'Big Pecks', 1: 'Overcoat', 'H': 'Weak Armor'}}
    Mandibuzz = {'abilities': {0: 'Big Pecks', 1: 'Overcoat', 'H': 'Weak Armor'}}
    Heatmor = {'abilities': {0: 'Gluttony', 1: 'Flash Fire', 'H': 'White Smoke'}}
    Durant = {'abilities': {0: 'Swarm', 1: 'Hustle', 'H': 'Truant'}}
    Deino = {'abilities': {0: 'Hustle'}}
    Zweilous = {'abilities': {0: 'Hustle'}}
    Hydreigon = {'abilities': {0: 'Levitate'}}
    Larvesta = {'abilities': {0: 'Flame Body', 'H': 'Swarm'}}
    Volcarona = {'abilities': {0: 'Flame Body', 'H': 'Swarm'}}
    Cobalion = {'abilities': {0: 'Justified'}}
    Terrakion = {'abilities': {0: 'Justified'}}
    Virizion = {'abilities': {0: 'Justified'}}
    Tornadus = {'abilities': {0: 'Prankster', 'H': 'Defiant'}}
    Tornadustherian = {'abilities': {0: 'Regenerator'}}
    Thundurus = {'abilities': {0: 'Prankster', 'H': 'Defiant'}}
    Thundurustherian = {'abilities': {0: 'Volt Absorb'}}
    Reshiram = {'abilities': {0: 'Turboblaze'}}
    Zekrom = {'abilities': {0: 'Teravolt'}}
    Landorus = {'abilities': {0: 'Sand Force', 'H': 'Sheer Force'}}
    Landorustherian = {'abilities': {0: 'Intimidate'}}
    Kyurem = {'abilities': {0: 'Pressure'}}
    Kyuremblack = {'abilities': {0: 'Teravolt'}}
    Kyuremwhite = {'abilities': {0: 'Turboblaze'}}
    Keldeo = {'abilities': {0: 'Justified'}}
    Keldeoresolute = {'abilities': {0: 'Justified'}}
    Meloetta = {'abilities': {0: 'Serene Grace'}}
    Meloettapirouette = {'abilities': {0: 'Serene Grace'}}
    Genesect = {'abilities': {0: 'Download'}}
    Genesectdouse = {'abilities': {0: 'Download'}}
    Genesectshock = {'abilities': {0: 'Download'}}
    Genesectburn = {'abilities': {0: 'Download'}}
    Genesectchill = {'abilities': {0: 'Download'}}
    Chespin = {'abilities': {0: 'Overgrow', 'H': 'Bulletproof'}}
    Quilladin = {'abilities': {0: 'Overgrow', 'H': 'Bulletproof'}}
    Chesnaught = {'abilities': {0: 'Overgrow', 'H': 'Bulletproof'}}
    Fennekin = {'abilities': {0: 'Blaze', 'H': 'Magician'}}
    Braixen = {'abilities': {0: 'Blaze', 'H': 'Magician'}}
    Delphox = {'abilities': {0: 'Blaze', 'H': 'Magician'}}
    Froakie = {'abilities': {0: 'Torrent', 'H': 'Protean'}}
    Frogadier = {'abilities': {0: 'Torrent', 'H': 'Protean'}}
    Greninja = {'abilities': {0: 'Torrent', 'H': 'Protean', 'S': 'Battle Bond'}}
    Greninjaash = {'abilities': {0: 'Battle Bond'}}
    Bunnelby = {'abilities': {0: 'Pickup', 1: 'Cheek Pouch', 'H': 'Huge Power'}}
    Diggersby = {'abilities': {0: 'Pickup', 1: 'Cheek Pouch', 'H': 'Huge Power'}}
    Fletchling = {'abilities': {0: 'Big Pecks', 'H': 'Gale Wings'}}
    Fletchinder = {'abilities': {0: 'Flame Body', 'H': 'Gale Wings'}}
    Talonflame = {'abilities': {0: 'Flame Body', 'H': 'Gale Wings'}}
    Scatterbug = {'abilities': {0: 'Shield Dust', 1: 'Compound Eyes', 'H': 'Friend Guard'}}
    Spewpa = {'abilities': {0: 'Shed Skin', 'H': 'Friend Guard'}}
    Vivillon = {'abilities': {0: 'Shield Dust', 1: 'Compound Eyes', 'H': 'Friend Guard'}}
    Vivillonfancy = {'abilities': {0: 'Shield Dust', 1: 'Compound Eyes'}}
    Vivillonpokeball = {'abilities': {0: 'Shield Dust', 1: 'Compound Eyes'}}
    Litleo = {'abilities': {0: 'Rivalry', 1: 'Unnerve', 'H': 'Moxie'}}
    Pyroar = {'abilities': {0: 'Rivalry', 1: 'Unnerve', 'H': 'Moxie'}}
    Flabebe = {'abilities': {0: 'Flower Veil', 'H': 'Symbiosis'}}
    Floette = {'abilities': {0: 'Flower Veil', 'H': 'Symbiosis'}}
    Floetteeternal = {'abilities': {0: 'Flower Veil'}}
    Florges = {'abilities': {0: 'Flower Veil', 'H': 'Symbiosis'}}
    Skiddo = {'abilities': {0: 'Sap Sipper', 'H': 'Grass Pelt'}}
    Gogoat = {'abilities': {0: 'Sap Sipper', 'H': 'Grass Pelt'}}
    Pancham = {'abilities': {0: 'Iron Fist', 1: 'Mold Breaker', 'H': 'Scrappy'}}
    Pangoro = {'abilities': {0: 'Iron Fist', 1: 'Mold Breaker', 'H': 'Scrappy'}}
    Furfrou = {'abilities': {0: 'Fur Coat'}}
    Espurr = {'abilities': {0: 'Keen Eye', 1: 'Infiltrator', 'H': 'Own Tempo'}}
    Meowstic = {'abilities': {0: 'Keen Eye', 1: 'Infiltrator', 'H': 'Prankster'}}
    Meowsticf = {'abilities': {0: 'Keen Eye', 1: 'Infiltrator', 'H': 'Competitive'}}
    Honedge = {'abilities': {0: 'No Guard'}}
    Doublade = {'abilities': {0: 'No Guard'}}
    Aegislash = {'abilities': {0: 'Stance Change'}}
    Aegislashblade = {'abilities': {0: 'Stance Change'}}
    Spritzee = {'abilities': {0: 'Healer', 'H': 'Aroma Veil'}}
    Aromatisse = {'abilities': {0: 'Healer', 'H': 'Aroma Veil'}}
    Swirlix = {'abilities': {0: 'Sweet Veil', 'H': 'Unburden'}}
    Slurpuff = {'abilities': {0: 'Sweet Veil', 'H': 'Unburden'}}
    Inkay = {'abilities': {0: 'Contrary', 1: 'Suction Cups', 'H': 'Infiltrator'}}
    Malamar = {'abilities': {0: 'Contrary', 1: 'Suction Cups', 'H': 'Infiltrator'}}
    Binacle = {'abilities': {0: 'Tough Claws', 1: 'Sniper', 'H': 'Pickpocket'}}
    Barbaracle = {'abilities': {0: 'Tough Claws', 1: 'Sniper', 'H': 'Pickpocket'}}
    Skrelp = {'abilities': {0: 'Poison Point', 1: 'Poison Touch', 'H': 'Adaptability'}}
    Dragalge = {'abilities': {0: 'Poison Point', 1: 'Poison Touch', 'H': 'Adaptability'}}
    Clauncher = {'abilities': {0: 'Mega Launcher'}}
    Clawitzer = {'abilities': {0: 'Mega Launcher'}}
    Helioptile = {'abilities': {0: 'Dry Skin', 1: 'Sand Veil', 'H': 'Solar Power'}}
    Heliolisk = {'abilities': {0: 'Dry Skin', 1: 'Sand Veil', 'H': 'Solar Power'}}
    Tyrunt = {'abilities': {0: 'Strong Jaw', 'H': 'Sturdy'}}
    Tyrantrum = {'abilities': {0: 'Strong Jaw', 'H': 'Rock Head'}}
    Amaura = {'abilities': {0: 'Refrigerate', 'H': 'Snow Warning'}}
    Aurorus = {'abilities': {0: 'Refrigerate', 'H': 'Snow Warning'}}
    Sylveon = {'abilities': {0: 'Cute Charm', 'H': 'Pixilate'}}
    Hawlucha = {'abilities': {0: 'Limber', 1: 'Unburden', 'H': 'Mold Breaker'}}
    Dedenne = {'abilities': {0: 'Cheek Pouch', 1: 'Pickup', 'H': 'Plus'}}
    Carbink = {'abilities': {0: 'Clear Body', 'H': 'Sturdy'}}
    Goomy = {'abilities': {0: 'Sap Sipper', 1: 'Hydration', 'H': 'Gooey'}}
    Sliggoo = {'abilities': {0: 'Sap Sipper', 1: 'Hydration', 'H': 'Gooey'}}
    Goodra = {'abilities': {0: 'Sap Sipper', 1: 'Hydration', 'H': 'Gooey'}}
    Klefki = {'abilities': {0: 'Prankster', 'H': 'Magician'}}
    Phantump = {'abilities': {0: 'Natural Cure', 1: 'Frisk', 'H': 'Harvest'}}
    Trevenant = {'abilities': {0: 'Natural Cure', 1: 'Frisk', 'H': 'Harvest'}}
    Pumpkaboo = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Pumpkaboosmall = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Pumpkaboolarge = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Pumpkaboosuper = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Gourgeist = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Gourgeistsmall = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Gourgeistlarge = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Gourgeistsuper = {'abilities': {0: 'Pickup', 1: 'Frisk', 'H': 'Insomnia'}}
    Bergmite = {'abilities': {0: 'Own Tempo', 1: 'Ice Body', 'H': 'Sturdy'}}
    Avalugg = {'abilities': {0: 'Own Tempo', 1: 'Ice Body', 'H': 'Sturdy'}}
    Noibat = {'abilities': {0: 'Frisk', 1: 'Infiltrator', 'H': 'Telepathy'}}
    Noivern = {'abilities': {0: 'Frisk', 1: 'Infiltrator', 'H': 'Telepathy'}}
    Xerneas = {'abilities': {0: 'Fairy Aura'}}
    Xerneasneutral = {'abilities': {0: 'Fairy Aura'}}
    Yveltal = {'abilities': {0: 'Dark Aura'}}
    Zygarde = {'abilities': {0: 'Aura Break', 'S': 'Power Construct'}}
    Zygardecomplete = {'abilities': {0: 'Power Construct'}}
    Diancie = {'abilities': {0: 'Clear Body'}}
    Dianciemega = {'abilities': {0: 'Magic Bounce'}}
    Hoopa = {'abilities': {0: 'Magician'}}
    Hoopaunbound = {'abilities': {0: 'Magician'}}
    Volcanion = {'abilities': {0: 'Water Absorb'}}
    Rowlet = {'abilities': {0: 'Overgrow', 'H': 'Long Reach'}}
    Dartrix = {'abilities': {0: 'Overgrow', 'H': 'Long Reach'}}
    Decidueye = {'abilities': {0: 'Overgrow', 'H': 'Long Reach'}}
    Litten = {'abilities': {0: 'Blaze', 'H': 'Intimidate'}}
    Torracat = {'abilities': {0: 'Blaze', 'H': 'Intimidate'}}
    Incineroar = {'abilities': {0: 'Blaze', 'H': 'Intimidate'}}
    Popplio = {'abilities': {0: 'Torrent', 'H': 'Liquid Voice'}}
    Brionne = {'abilities': {0: 'Torrent', 'H': 'Liquid Voice'}}
    Primarina = {'abilities': {0: 'Torrent', 'H': 'Liquid Voice'}}
    Pikipek = {'abilities': {0: 'Keen Eye', 1: 'Skill Link', 'H': 'Pickup'}}
    Trumbeak = {'abilities': {0: 'Keen Eye', 1: 'Skill Link', 'H': 'Pickup'}}
    Toucannon = {'abilities': {0: 'Keen Eye', 1: 'Skill Link', 'H': 'Sheer Force'}}
    Yungoos = {'abilities': {0: 'Stakeout', 1: 'Strong Jaw', 'H': 'Adaptability'}}
    Gumshoos = {'abilities': {0: 'Stakeout', 1: 'Strong Jaw', 'H': 'Adaptability'}}
    Gumshoostotem = {'abilities': {0: 'Adaptability'}}
    Grubbin = {'abilities': {0: 'Swarm'}}
    Charjabug = {'abilities': {0: 'Battery'}}
    Vikavolt = {'abilities': {0: 'Levitate'}}
    Vikavolttotem = {'abilities': {0: 'Levitate'}}
    Crabrawler = {'abilities': {0: 'Hyper Cutter', 1: 'Iron Fist', 'H': 'Anger Point'}}
    Crabominable = {'abilities': {0: 'Hyper Cutter', 1: 'Iron Fist', 'H': 'Anger Point'}}
    Oricorio = {'abilities': {0: 'Dancer'}}
    Oricoriopompom = {'abilities': {0: 'Dancer'}}
    Oricoriopau = {'abilities': {0: 'Dancer'}}
    Oricoriosensu = {'abilities': {0: 'Dancer'}}
    Cutiefly = {'abilities': {0: 'Honey Gather', 1: 'Shield Dust', 'H': 'Sweet Veil'}}
    Ribombee = {'abilities': {0: 'Honey Gather', 1: 'Shield Dust', 'H': 'Sweet Veil'}}
    Ribombeetotem = {'abilities': {0: 'Sweet Veil'}}
    Rockruff = {'abilities': {0: 'Keen Eye', 1: 'Vital Spirit', 'H': 'Steadfast', 'S': 'Own Tempo'}}
    Lycanroc = {'abilities': {0: 'Keen Eye', 1: 'Sand Rush', 'H': 'Steadfast'}}
    Lycanrocmidnight = {'abilities': {0: 'Keen Eye', 1: 'Vital Spirit', 'H': 'No Guard'}}
    Lycanrocdusk = {'abilities': {0: 'Tough Claws'}}
    Wishiwashi = {'abilities': {0: 'Schooling'}}
    Wishiwashischool = {'abilities': {0: 'Schooling'}}
    Mareanie = {'abilities': {0: 'Merciless', 1: 'Limber', 'H': 'Regenerator'}}
    Toxapex = {'abilities': {0: 'Merciless', 1: 'Limber', 'H': 'Regenerator'}}
    Mudbray = {'abilities': {0: 'Own Tempo', 1: 'Stamina', 'H': 'Inner Focus'}}
    Mudsdale = {'abilities': {0: 'Own Tempo', 1: 'Stamina', 'H': 'Inner Focus'}}
    Dewpider = {'abilities': {0: 'Water Bubble', 'H': 'Water Absorb'}}
    Araquanid = {'abilities': {0: 'Water Bubble', 'H': 'Water Absorb'}}
    Araquanidtotem = {'abilities': {0: 'Water Bubble'}}
    Fomantis = {'abilities': {0: 'Leaf Guard', 'H': 'Contrary'}}
    Lurantis = {'abilities': {0: 'Leaf Guard', 'H': 'Contrary'}}
    Lurantistotem = {'abilities': {0: 'Leaf Guard'}}
    Morelull = {'abilities': {0: 'Illuminate', 1: 'Effect Spore', 'H': 'Rain Dish'}}
    Shiinotic = {'abilities': {0: 'Illuminate', 1: 'Effect Spore', 'H': 'Rain Dish'}}
    Salandit = {'abilities': {0: 'Corrosion', 'H': 'Oblivious'}}
    Salazzle = {'abilities': {0: 'Corrosion', 'H': 'Oblivious'}}
    Salazzletotem = {'abilities': {0: 'Corrosion'}}
    Stufful = {'abilities': {0: 'Fluffy', 1: 'Klutz', 'H': 'Cute Charm'}}
    Bewear = {'abilities': {0: 'Fluffy', 1: 'Klutz', 'H': 'Unnerve'}}
    Bounsweet = {'abilities': {0: 'Leaf Guard', 1: 'Oblivious', 'H': 'Sweet Veil'}}
    Steenee = {'abilities': {0: 'Leaf Guard', 1: 'Oblivious', 'H': 'Sweet Veil'}}
    Tsareena = {'abilities': {0: 'Leaf Guard', 1: 'Queenly Majesty', 'H': 'Sweet Veil'}}
    Comfey = {'abilities': {0: 'Flower Veil', 1: 'Triage', 'H': 'Natural Cure'}}
    Oranguru = {'abilities': {0: 'Inner Focus', 1: 'Telepathy', 'H': 'Symbiosis'}}
    Passimian = {'abilities': {0: 'Receiver', 'H': 'Defiant'}}
    Wimpod = {'abilities': {0: 'Wimp Out'}}
    Golisopod = {'abilities': {0: 'Emergency Exit'}}
    Sandygast = {'abilities': {0: 'Water Compaction', 'H': 'Sand Veil'}}
    Palossand = {'abilities': {0: 'Water Compaction', 'H': 'Sand Veil'}}
    Pyukumuku = {'abilities': {0: 'Innards Out', 'H': 'Unaware'}}
    Typenull = {'abilities': {0: 'Battle Armor'}}
    Silvally = {'abilities': {0: 'RKS System'}}
    Silvallybug = {'abilities': {0: 'RKS System'}}
    Silvallydark = {'abilities': {0: 'RKS System'}}
    Silvallydragon = {'abilities': {0: 'RKS System'}}
    Silvallyelectric = {'abilities': {0: 'RKS System'}}
    Silvallyfairy = {'abilities': {0: 'RKS System'}}
    Silvallyfighting = {'abilities': {0: 'RKS System'}}
    Silvallyfire = {'abilities': {0: 'RKS System'}}
    Silvallyflying = {'abilities': {0: 'RKS System'}}
    Silvallyghost = {'abilities': {0: 'RKS System'}}
    Silvallygrass = {'abilities': {0: 'RKS System'}}
    Silvallyground = {'abilities': {0: 'RKS System'}}
    Silvallyice = {'abilities': {0: 'RKS System'}}
    Silvallypoison = {'abilities': {0: 'RKS System'}}
    Silvallypsychic = {'abilities': {0: 'RKS System'}}
    Silvallyrock = {'abilities': {0: 'RKS System'}}
    Silvallysteel = {'abilities': {0: 'RKS System'}}
    Silvallywater = {'abilities': {0: 'RKS System'}}
    Minior = {'abilities': {0: 'Shields Down'}}
    Miniormeteor = {'abilities': {0: 'Shields Down'}}
    Komala = {'abilities': {0: 'Comatose'}}
    Turtonator = {'abilities': {0: 'Shell Armor'}}
    Togedemaru = {'abilities': {0: 'Iron Barbs', 1: 'Lightning Rod', 'H': 'Sturdy'}}
    Togedemarutotem = {'abilities': {0: 'Sturdy'}}
    Mimikyu = {'abilities': {0: 'Disguise'}}
    Mimikyubusted = {'abilities': {0: 'Disguise'}}
    Mimikyutotem = {'abilities': {0: 'Disguise'}}
    Mimikyubustedtotem = {'abilities': {0: 'Disguise'}}
    Bruxish = {'abilities': {0: 'Dazzling', 1: 'Strong Jaw', 'H': 'Wonder Skin'}}
    Drampa = {'abilities': {0: 'Berserk', 1: 'Sap Sipper', 'H': 'Cloud Nine'}}
    Dhelmise = {'abilities': {0: 'Steelworker'}}
    Jangmoo = {'abilities': {0: 'Bulletproof', 1: 'Soundproof', 'H': 'Overcoat'}}
    Hakamoo = {'abilities': {0: 'Bulletproof', 1: 'Soundproof', 'H': 'Overcoat'}}
    Kommoo = {'abilities': {0: 'Bulletproof', 1: 'Soundproof', 'H': 'Overcoat'}}
    Kommoototem = {'abilities': {0: 'Overcoat'}}
    Tapukoko = {'abilities': {0: 'Electric Surge', 'H': 'Telepathy'}}
    Tapulele = {'abilities': {0: 'Psychic Surge', 'H': 'Telepathy'}}
    Tapubulu = {'abilities': {0: 'Grassy Surge', 'H': 'Telepathy'}}
    Tapufini = {'abilities': {0: 'Misty Surge', 'H': 'Telepathy'}}
    Cosmog = {'abilities': {0: 'Unaware'}}
    Cosmoem = {'abilities': {0: 'Sturdy'}}
    Solgaleo = {'abilities': {0: 'Full Metal Body'}}
    Lunala = {'abilities': {0: 'Shadow Shield'}}
    Nihilego = {'abilities': {0: 'Beast Boost'}}
    Buzzwole = {'abilities': {0: 'Beast Boost'}}
    Pheromosa = {'abilities': {0: 'Beast Boost'}}
    Xurkitree = {'abilities': {0: 'Beast Boost'}}
    Celesteela = {'abilities': {0: 'Beast Boost'}}
    Kartana = {'abilities': {0: 'Beast Boost'}}
    Guzzlord = {'abilities': {0: 'Beast Boost'}}
    Necrozma = {'abilities': {0: 'Prism Armor'}}
    Necrozmaduskmane = {'abilities': {0: 'Prism Armor'}}
    Necrozmadawnwings = {'abilities': {0: 'Prism Armor'}}
    Necrozmaultra = {'abilities': {0: 'Neuroforce'}}
    Magearna = {'abilities': {0: 'Soul-Heart'}}
    Magearnaoriginal = {'abilities': {0: 'Soul-Heart'}}
    Marshadow = {'abilities': {0: 'Technician'}}
    Poipole = {'abilities': {0: 'Beast Boost'}}
    Naganadel = {'abilities': {0: 'Beast Boost'}}
    Stakataka = {'abilities': {0: 'Beast Boost'}}
    Blacephalon = {'abilities': {0: 'Beast Boost'}}
    Zeraora = {'abilities': {0: 'Volt Absorb'}}
    Meltan = {'abilities': {0: 'Magnet Pull'}}
    Melmetal = {'abilities': {0: 'Iron Fist'}}
    Melmetalgmax = {'abilities': {0: 'Iron Fist'}}
    Grookey = {'abilities': {0: 'Overgrow', 'H': 'Grassy Surge'}}
    Thwackey = {'abilities': {0: 'Overgrow', 'H': 'Grassy Surge'}}
    Rillaboom = {'abilities': {0: 'Overgrow', 'H': 'Grassy Surge'}}
    Rillaboomgmax = {'abilities': {0: 'Overgrow', 'H': 'Grassy Surge'}}
    Scorbunny = {'abilities': {0: 'Blaze', 'H': 'Libero'}}
    Raboot = {'abilities': {0: 'Blaze', 'H': 'Libero'}}
    Cinderace = {'abilities': {0: 'Blaze', 'H': 'Libero'}}
    Cinderacegmax = {'abilities': {0: 'Blaze', 'H': 'Libero'}}
    Sobble = {'abilities': {0: 'Torrent', 'H': 'Sniper'}}
    Drizzile = {'abilities': {0: 'Torrent', 'H': 'Sniper'}}
    Inteleon = {'abilities': {0: 'Torrent', 'H': 'Sniper'}}
    Inteleongmax = {'abilities': {0: 'Torrent', 'H': 'Sniper'}}
    Skwovet = {'abilities': {0: 'Cheek Pouch', 'H': 'Gluttony'}}
    Greedent = {'abilities': {0: 'Cheek Pouch', 'H': 'Gluttony'}}
    Rookidee = {'abilities': {0: 'Keen Eye', 1: 'Unnerve', 'H': 'Big Pecks'}}
    Corvisquire = {'abilities': {0: 'Keen Eye', 1: 'Unnerve', 'H': 'Big Pecks'}}
    Corviknight = {'abilities': {0: 'Pressure', 1: 'Unnerve', 'H': 'Mirror Armor'}}
    Corviknightgmax = {'abilities': {0: 'Pressure', 1: 'Unnerve', 'H': 'Mirror Armor'}}
    Blipbug = {'abilities': {0: 'Swarm', 1: 'Compound Eyes', 'H': 'Telepathy'}}
    Dottler = {'abilities': {0: 'Swarm', 1: 'Compound Eyes', 'H': 'Telepathy'}}
    Orbeetle = {'abilities': {0: 'Swarm', 1: 'Frisk', 'H': 'Telepathy'}}
    Orbeetlegmax = {'abilities': {0: 'Swarm', 1: 'Frisk', 'H': 'Telepathy'}}
    Nickit = {'abilities': {0: 'Run Away', 1: 'Unburden', 'H': 'Stakeout'}}
    Thievul = {'abilities': {0: 'Run Away', 1: 'Unburden', 'H': 'Stakeout'}}
    Gossifleur = {'abilities': {0: 'Cotton Down', 1: 'Regenerator', 'H': 'Effect Spore'}}
    Eldegoss = {'abilities': {0: 'Cotton Down', 1: 'Regenerator', 'H': 'Effect Spore'}}
    Wooloo = {'abilities': {0: 'Fluffy', 1: 'Run Away', 'H': 'Bulletproof'}}
    Dubwool = {'abilities': {0: 'Fluffy', 1: 'Steadfast', 'H': 'Bulletproof'}}
    Chewtle = {'abilities': {0: 'Strong Jaw', 1: 'Shell Armor', 'H': 'Swift Swim'}}
    Drednaw = {'abilities': {0: 'Strong Jaw', 1: 'Shell Armor', 'H': 'Swift Swim'}}
    Drednawgmax = {'abilities': {0: 'Strong Jaw', 1: 'Shell Armor', 'H': 'Swift Swim'}}
    Yamper = {'abilities': {0: 'Ball Fetch', 'H': 'Rattled'}}
    Boltund = {'abilities': {0: 'Strong Jaw', 'H': 'Competitive'}}
    Rolycoly = {'abilities': {0: 'Steam Engine', 1: 'Heatproof', 'H': 'Flash Fire'}}
    Carkol = {'abilities': {0: 'Steam Engine', 1: 'Flame Body', 'H': 'Flash Fire'}}
    Coalossal = {'abilities': {0: 'Steam Engine', 1: 'Flame Body', 'H': 'Flash Fire'}}
    Coalossalgmax = {'abilities': {0: 'Steam Engine', 1: 'Flame Body', 'H': 'Flash Fire'}}
    Applin = {'abilities': {0: 'Ripen', 1: 'Gluttony', 'H': 'Bulletproof'}}
    Flapple = {'abilities': {0: 'Ripen', 1: 'Gluttony', 'H': 'Hustle'}}
    Flapplegmax = {'abilities': {0: 'Ripen', 1: 'Gluttony', 'H': 'Hustle'}}
    Appletun = {'abilities': {0: 'Ripen', 1: 'Gluttony', 'H': 'Thick Fat'}}
    Appletungmax = {'abilities': {0: 'Ripen', 1: 'Gluttony', 'H': 'Thick Fat'}}
    Silicobra = {'abilities': {0: 'Sand Spit', 1: 'Shed Skin', 'H': 'Sand Veil'}}
    Sandaconda = {'abilities': {0: 'Sand Spit', 1: 'Shed Skin', 'H': 'Sand Veil'}}
    Sandacondagmax = {'abilities': {0: 'Sand Spit', 1: 'Shed Skin', 'H': 'Sand Veil'}}
    Cramorant = {'abilities': {0: 'Gulp Missile'}}
    Cramorantgulping = {'abilities': {0: 'Gulp Missile'}}
    Cramorantgorging = {'abilities': {0: 'Gulp Missile'}}
    Arrokuda = {'abilities': {0: 'Swift Swim', 'H': 'Propeller Tail'}}
    Barraskewda = {'abilities': {0: 'Swift Swim', 'H': 'Propeller Tail'}}
    Toxel = {'abilities': {0: 'Rattled', 1: 'Static', 'H': 'Klutz'}}
    Toxtricity = {'abilities': {0: 'Punk Rock', 1: 'Plus', 'H': 'Technician'}}
    Toxtricitylowkey = {'abilities': {0: 'Punk Rock', 1: 'Minus', 'H': 'Technician'}}
    Toxtricitygmax = {'abilities': {0: 'Punk Rock', 1: 'Plus', 'H': 'Technician'}}
    Toxtricitylowkeygmax = {'abilities': {0: 'Punk Rock', 1: 'Minus', 'H': 'Technician'}}
    Sizzlipede = {'abilities': {0: 'Flash Fire', 1: 'White Smoke', 'H': 'Flame Body'}}
    Centiskorch = {'abilities': {0: 'Flash Fire', 1: 'White Smoke', 'H': 'Flame Body'}}
    Centiskorchgmax = {'abilities': {0: 'Flash Fire', 1: 'White Smoke', 'H': 'Flame Body'}}
    Clobbopus = {'abilities': {0: 'Limber', 'H': 'Technician'}}
    Grapploct = {'abilities': {0: 'Limber', 'H': 'Technician'}}
    Sinistea = {'abilities': {0: 'Weak Armor', 'H': 'Cursed Body'}}
    Sinisteaantique = {'abilities': {0: 'Weak Armor', 'H': 'Cursed Body'}}
    Polteageist = {'abilities': {0: 'Weak Armor', 'H': 'Cursed Body'}}
    Polteageistantique = {'abilities': {0: 'Weak Armor', 'H': 'Cursed Body'}}
    Hatenna = {'abilities': {0: 'Healer', 1: 'Anticipation', 'H': 'Magic Bounce'}}
    Hattrem = {'abilities': {0: 'Healer', 1: 'Anticipation', 'H': 'Magic Bounce'}}
    Hatterene = {'abilities': {0: 'Healer', 1: 'Anticipation', 'H': 'Magic Bounce'}}
    Hatterenegmax = {'abilities': {0: 'Healer', 1: 'Anticipation', 'H': 'Magic Bounce'}}
    Impidimp = {'abilities': {0: 'Prankster', 1: 'Frisk', 'H': 'Pickpocket'}}
    Morgrem = {'abilities': {0: 'Prankster', 1: 'Frisk', 'H': 'Pickpocket'}}
    Grimmsnarl = {'abilities': {0: 'Prankster', 1: 'Frisk', 'H': 'Pickpocket'}}
    Grimmsnarlgmax = {'abilities': {0: 'Prankster', 1: 'Frisk', 'H': 'Pickpocket'}}
    Obstagoon = {'abilities': {0: 'Reckless', 1: 'Guts', 'H': 'Defiant'}}
    Perrserker = {'abilities': {0: 'Battle Armor', 1: 'Tough Claws', 'H': 'Steely Spirit'}}
    Cursola = {'abilities': {0: 'Weak Armor', 'H': 'Perish Body'}}
    Sirfetchd = {'abilities': {0: 'Steadfast', 'H': 'Scrappy'}}
    Mrrime = {'abilities': {0: 'Tangled Feet', 1: 'Screen Cleaner', 'H': 'Ice Body'}}
    Runerigus = {'abilities': {0: 'Wandering Spirit'}}
    Milcery = {'abilities': {0: 'Sweet Veil', 'H': 'Aroma Veil'}}
    Alcremie = {'abilities': {0: 'Sweet Veil', 'H': 'Aroma Veil'}}
    Alcremiegmax = {'abilities': {0: 'Sweet Veil', 'H': 'Aroma Veil'}}
    Falinks = {'abilities': {0: 'Battle Armor', 'H': 'Defiant'}}
    Pincurchin = {'abilities': {0: 'Lightning Rod', 'H': 'Electric Surge'}}
    Snom = {'abilities': {0: 'Shield Dust', 'H': 'Ice Scales'}}
    Frosmoth = {'abilities': {0: 'Shield Dust', 'H': 'Ice Scales'}}
    Stonjourner = {'abilities': {0: 'Power Spot'}}
    Eiscue = {'abilities': {0: 'Ice Face'}}
    Eiscuenoice = {'abilities': {0: 'Ice Face'}}
    Indeedee = {'abilities': {0: 'Inner Focus', 1: 'Synchronize', 'H': 'Psychic Surge'}}
    Indeedeef = {'abilities': {0: 'Own Tempo', 1: 'Synchronize', 'H': 'Psychic Surge'}}
    Morpeko = {'abilities': {0: 'Hunger Switch'}}
    Morpekohangry = {'abilities': {0: 'Hunger Switch'}}
    Cufant = {'abilities': {0: 'Sheer Force', 'H': 'Heavy Metal'}}
    Copperajah = {'abilities': {0: 'Sheer Force', 'H': 'Heavy Metal'}}
    Copperajahgmax = {'abilities': {0: 'Sheer Force', 'H': 'Heavy Metal'}}
    Dracozolt = {'abilities': {0: 'Volt Absorb', 1: 'Hustle', 'H': 'Sand Rush'}}
    Arctozolt = {'abilities': {0: 'Volt Absorb', 1: 'Static', 'H': 'Slush Rush'}}
    Dracovish = {'abilities': {0: 'Water Absorb', 1: 'Strong Jaw', 'H': 'Sand Rush'}}
    Arctovish = {'abilities': {0: 'Water Absorb', 1: 'Ice Body', 'H': 'Slush Rush'}}
    Duraludon = {'abilities': {0: 'Light Metal', 1: 'Heavy Metal', 'H': 'Stalwart'}}
    Duraludongmax = {'abilities': {0: 'Light Metal', 1: 'Heavy Metal', 'H': 'Stalwart'}}
    Dreepy = {'abilities': {0: 'Clear Body', 1: 'Infiltrator', 'H': 'Cursed Body'}}
    Drakloak = {'abilities': {0: 'Clear Body', 1: 'Infiltrator', 'H': 'Cursed Body'}}
    Dragapult = {'abilities': {0: 'Clear Body', 1: 'Infiltrator', 'H': 'Cursed Body'}}
    Zacian = {'abilities': {0: 'Intrepid Sword'}}
    Zaciancrowned = {'abilities': {0: 'Intrepid Sword'}}
    Zamazenta = {'abilities': {0: 'Dauntless Shield'}}
    Zamazentacrowned = {'abilities': {0: 'Dauntless Shield'}}
    Eternatus = {'abilities': {0: 'Pressure'}}
    Eternatuseternamax = {'abilities': {0: 'Pressure'}}
    Kubfu = {'abilities': {0: 'Inner Focus'}}
    Urshifu = {'abilities': {0: 'Unseen Fist'}}
    Urshifurapidstrike = {'abilities': {0: 'Unseen Fist'}}
    Urshifugmax = {'abilities': {0: 'Unseen Fist'}}
    Urshifurapidstrikegmax = {'abilities': {0: 'Unseen Fist'}}
    Zarude = {'abilities': {0: 'Leaf Guard'}}
    Zarudedada = {'abilities': {0: 'Leaf Guard'}}
    Regieleki = {'abilities': {0: 'Transistor'}}
    Regidrago = {'abilities': {0: "Dragon's Maw"}}
    Glastrier = {'abilities': {0: 'Chilling Neigh'}}
    Spectrier = {'abilities': {0: 'Grim Neigh'}}
    Calyrex = {'abilities': {0: 'Unnerve'}}
    Calyrexice = {'abilities': {0: 'As One (Glastrier)'}}
    Calyrexshadow = {'abilities': {0: 'As One (Spectrier)'}}
    Missingno = {'abilities': {0: ''}}
    Syclar = {'abilities': {0: 'Compound Eyes', 1: 'Snow Cloak', 'H': 'Ice Body'}}
    Syclant = {'abilities': {0: 'Compound Eyes', 1: 'Mountaineer', 'H': 'Ice Body'}}
    Revenankh = {'abilities': {0: 'Shed Skin', 1: 'Air Lock', 'H': 'Triage'}}
    Embirch = {'abilities': {0: 'Reckless', 1: 'Leaf Guard', 'H': 'Chlorophyll'}}
    Flarelm = {'abilities': {0: 'Rock Head', 1: 'Battle Armor', 'H': 'White Smoke'}}
    Pyroak = {'abilities': {0: 'Rock Head', 1: 'Battle Armor', 'H': 'White Smoke'}}
    Breezi = {'abilities': {0: 'Unburden', 1: 'Own Tempo', 'H': 'Frisk'}}
    Fidgit = {'abilities': {0: 'Persistent', 1: 'Vital Spirit', 'H': 'Frisk'}}
    Rebble = {'abilities': {0: 'Levitate', 1: 'Solid Rock', 'H': 'Sniper'}}
    Tactite = {'abilities': {0: 'Levitate', 1: 'Technician', 'H': 'Sniper'}}
    Stratagem = {'abilities': {0: 'Levitate', 1: 'Technician', 'H': 'Sniper'}}
    Privatyke = {'abilities': {0: 'Unaware', 'H': 'Technician'}}
    Arghonaut = {'abilities': {0: 'Unaware', 'H': 'Technician'}}
    Kitsunoh = {'abilities': {0: 'Frisk', 1: 'Limber', 'H': 'Iron Fist'}}
    Cyclohm = {'abilities': {0: 'Shield Dust', 1: 'Static', 'H': 'Damp'}}
    Colossoil = {'abilities': {0: 'Rebound', 1: 'Guts', 'H': 'Unnerve'}}
    Krilowatt = {'abilities': {0: 'Trace', 1: 'Magic Guard', 'H': 'Minus'}}
    Voodoll = {'abilities': {0: 'Volt Absorb', 1: 'Lightning Rod', 'H': 'Cursed Body'}}
    Voodoom = {'abilities': {0: 'Volt Absorb', 1: 'Lightning Rod', 'H': 'Cursed Body'}}
    Scratchet = {'abilities': {0: 'Scrappy', 1: 'Prankster', 'H': 'Vital Spirit'}}
    Tomohawk = {'abilities': {0: 'Intimidate', 1: 'Prankster', 'H': 'Justified'}}
    Necturine = {'abilities': {0: 'Anticipation', 'H': 'Telepathy'}}
    Necturna = {'abilities': {0: 'Forewarn', 'H': 'Telepathy'}}
    Mollux = {'abilities': {0: 'Dry Skin', 'H': 'Illuminate'}}
    Cupra = {'abilities': {0: 'Shield Dust', 1: 'Keen Eye', 'H': 'Magic Guard'}}
    Argalis = {'abilities': {0: 'Shed Skin', 1: 'Compound Eyes', 'H': 'Overcoat'}}
    Aurumoth = {'abilities': {0: 'Weak Armor', 1: 'No Guard', 'H': 'Light Metal'}}
    Brattler = {'abilities': {0: 'Harvest', 1: 'Infiltrator', 'H': 'Rattled'}}
    Malaconda = {'abilities': {0: 'Harvest', 1: 'Infiltrator', 'H': 'Drought'}}
    Cawdet = {'abilities': {0: 'Keen Eye', 1: 'Volt Absorb', 'H': 'Big Pecks'}}
    Cawmodore = {'abilities': {0: 'Intimidate', 1: 'Volt Absorb', 'H': 'Big Pecks'}}
    Volkritter = {'abilities': {0: 'Anticipation', 1: 'Infiltrator', 'H': 'Unnerve'}}
    Volkraken = {'abilities': {0: 'Analytic', 1: 'Infiltrator', 'H': 'Pressure'}}
    Snugglow = {'abilities': {0: 'Storm Drain', 1: 'Vital Spirit', 'H': 'Telepathy'}}
    Plasmanta = {'abilities': {0: 'Storm Drain', 1: 'Vital Spirit', 'H': 'Telepathy'}}
    Floatoy = {'abilities': {0: 'Water Veil', 1: 'Heatproof', 'H': 'Swift Swim'}}
    Caimanoe = {'abilities': {0: 'Water Veil', 1: 'Heatproof', 'H': 'Light Metal'}}
    Naviathan = {'abilities': {0: 'Guts', 1: 'Heatproof', 'H': 'Light Metal'}}
    Crucibelle = {'abilities': {0: 'Regenerator', 1: 'Mold Breaker', 'H': 'Liquid Ooze'}}
    Crucibellemega = {'abilities': {0: 'Magic Guard'}}
    Pluffle = {'abilities': {0: 'Natural Cure', 1: 'Aroma Veil', 'H': 'Friend Guard'}}
    Kerfluffle = {'abilities': {0: 'Natural Cure', 1: 'Aroma Veil', 'H': 'Friend Guard'}}
    Pajantom = {'abilities': {0: 'Comatose'}}
    Mumbao = {'abilities': {0: 'Solar Power', 1: 'Trace', 'H': 'Overcoat'}}
    Jumbao = {'abilities': {0: 'Drought', 1: 'Trace', 'H': 'Overcoat'}}
    Fawnifer = {'abilities': {0: 'Overgrow', 'H': 'Lightning Rod'}}
    Electrelk = {'abilities': {0: 'Overgrow', 'H': 'Galvanize'}}
    Caribolt = {'abilities': {0: 'Overgrow', 'H': 'Galvanize'}}
    Smogecko = {'abilities': {0: 'Blaze', 'H': 'Technician'}}
    Smoguana = {'abilities': {0: 'Blaze', 'H': 'Technician'}}
    Smokomodo = {'abilities': {0: 'Blaze', 'H': 'Technician'}}
    Swirlpool = {'abilities': {0: 'Torrent', 'H': 'Poison Heal'}}
    Coribalis = {'abilities': {0: 'Torrent', 'H': 'Poison Heal'}}
    Snaelstrom = {'abilities': {0: 'Torrent', 'H': 'Poison Heal'}}
    Justyke = {'abilities': {0: 'Levitate', 1: 'Stalwart', 'H': 'Justified'}}
    Equilibra = {'abilities': {0: 'Levitate', 1: 'Stalwart', 'H': 'Justified'}}
    Solotl = {'abilities': {0: 'Regenerator', 1: 'Vital Spirit', 'H': 'Magician'}}
    Astrolotl = {'abilities': {0: 'Regenerator', 1: 'Vital Spirit', 'H': 'Magician'}}
    Miasmite = {'abilities': {0: 'Neutralizing Gas', 1: 'Hyper Cutter', 'H': 'Compound Eyes'}}
    Miasmaw = {'abilities': {0: 'Neutralizing Gas', 1: 'Hyper Cutter', 'H': 'Compound Eyes'}}
