from enum import Enum, auto
class Natures(Enum):
    Adamant = auto()
    Bashful = auto()
    Bold = auto()
    Brave = auto()
    Calm = auto()
    Careful = auto()
    Docile = auto()
    Gentle = auto()
    Hardy = auto()
    Hasty = auto()
    Impish = auto()
    Jolly = auto()
    Lax = auto()
    Lonely = auto()
    Mild = auto()
    Modest = auto()
    Naive = auto()
    Naughty = auto()
    Quiet = auto()
    Quirky = auto()
    Rash = auto()
    Relaxed = auto()
    Sassy = auto()
    Serious = auto()
    Timid = auto()
